### ISSUE TITLE
Two @base => JsonValueImpl cannot be cast to class javax.json.JsonStructure

### ISSUE THREAD

**Issue by jmvanel** [filip26/titanium-json-ld#112]
**Describe the bug**
A `@base` in `@context` , and another `@base` in data block entails a ClassCastException: `class javax.json.JsonValueImpl cannot be cast to class javax.json.JsonStructure (javax.json.JsonValueImpl and javax.json.JsonStructure .`

**To Reproduce**
Call 
`JsonLd.toRdf(JsonDocument . of (is)). get()`
where InputStream `is` reads:
```json
{
  "@context": {
    "@base" : "https://beta.grottocenter.org/api/v1/entrances/"
  } ,
  "@base": "b",
  "@id": "4",
  "urn:name": "Prérouge (Grotte de)"
}
```
**Expected behavior**
No exception, of course.
https://json-ld.org/playground/ does not take in account  the `@base` in data block  .
Removing it removes the exception.

**Additional context**
Using latest Titanium 0.8.6 .
The stack is
```
java.lang.ClassCastException: class javax.json.JsonValueImpl cannot be cast to class javax.json.JsonStructure 
	at com.apicatalog.jsonld.flattening.NodeMapBuilder.build(NodeMapBuilder.java:389)
	at com.apicatalog.jsonld.flattening.NodeMapBuilder.build(NodeMapBuilder.java:122)
	at com.apicatalog.jsonld.processor.ToRdfProcessor.toRdf(ToRdfProcessor.java:73)
```

**Comment by filip26** [comment]
Good catch! Thank you for reporting it.
