### ISSUE TITLE
integer JSON value should be used for @id

### ISSUE THREAD

**Issue by jmvanel** [filip26/titanium-json-ld#120]
**Is feature request related to a problem?**
Integer id's are very common in JSON API's. Alas it is explicitly forbidden by JSON-LD, for bad reasons.

**Describe the proposed solution**
```json
{ "@context": {
  "id": "@id",
  "dwciri": "http://rs.tdwg.org/dwc/iri/",
  "taxonKey":{
    "@context": {
      "@base" : "https://api.gbif.org/v1/species/"
    },
    "@id": "dwciri:toTaxon", "@type": "@id"
  }
},
"id": 123 ,
"taxonKey": 7310533
}
```
Expected:
```turtle
<https://json-ld.org/playground/123> <http://rs.tdwg.org/dwc/iri/toTaxon>
  <https://api.gbif.org/v1/species/7310533> .
```
This is what is obtained in Playground when changing  123 and 7310533 to strings.
@filip26 suggested that "Titanium could support that as an extension. e,g, `JsonLdOptions.allowNumericId(boolean)`. " .
It could be the default, but that is debatable...

**Describe alternatives considered**
There is no alternative , except pre-processing the JSON, or post-processing with SPARQL.

**Additional context**
This issue on W3C has got some following: 
https://github.com/w3c/json-ld-api/issues/509
See previous issue with example:
https://github.com/json-ld/json-ld.org/issues/742

**Comment by filip26** [comment]
An experimental support has been added: `toRdf()`, `expand()`. 

e.g.
```java
JsonLd.toRdf(document).base("https://json-ld.org/playground/").numericId().get()
```

see
https://github.com/filip26/titanium-json-ld/blob/master/src/test/java/com/apicatalog/jsonld/issue/NumericId120Test.java

Please feel to re-open, raise a new issue.

**Comment by jmvanel** [comment]
I added this on my generic service in semantic-forms (SF), integrating this
issue on numeric id's, it gives (1) :
http://semantic-forms.cc:1952/json2rdf?src=https://beta.grottocenter.org/api/v1/entrances/4&context=https://github.com/jmvanel/Karstlink-ontology/raw/master/grottocenter.org_context.jsonld
I'm going to update the @context
https://github.com/jmvanel/Karstlink-ontology/raw/master/grottocenter.org_context.jsonld
Actually for now the default @context is this one, so this call gives the
same:
http://semantic-forms.cc:1952/json2rdf?src=https://beta.grottocenter.org/api
/v1/entrances/4
The goal remains to do without the wrapper
http://semantic-forms.cc:1952/json2rdf?src=, and for the API to be
modified, but this service allows debugging the @context and showing a
result.

Depending on the other JSON-LD project I have:
https://github.com/jmvanel/rdf-convert
I may extend the service /json2rdf to register a correspondence between a
JSON URL's prefix and the @context, like adding  this to URL (1):
&prefix=https://beta.grottocenter.org/api/v1/
After this call, any src URL starting with that prefix will apply the
recorded corresponding  @context .

The next step would be to integrate this feature into the regular SF user
interface: for any URL <JSON-URL> with JSON MIME type,
http://semantic-forms.cc:1952/display?displayuri=*<JSON-URL>*
will display prettily the triples, thus adding JSON MIME type to existing
content negotiation involving RDF, Turtle, JSON-LD, N-Triple MIME types.

Source code of the service:
https://github.com/jmvanel/semantic_forms/blob/master/scala/forms_play/app/controllers/Json2RDFServiceApp.scala#L63

Jean-Marc Vanel
<http://semantic-forms.cc:9112/display?displayuri=http://jmvanel.free.fr/jmv.rdf%23me>
+33
(0)6 89 16 29 52


Le jeu. 3 déc. 2020 à 20:36, Filip Kolarik <notifications@github.com> a
écrit :
