### ISSUE TITLE
HttpLoader doesn't properly process missing content-type

### ISSUE THREAD

**Issue by filip26** [filip26/titanium-json-ld#124]
**Describe the bug**
If received response doesn't have content-type then an exception is thrown

```Java
java.lang.IllegalArgumentException: The provided content type is null.
	at com.apicatalog.jsonld.document.DocumentParser.parse(DocumentParser.java:49)
	at com.apicatalog.jsonld.loader.HttpLoader.createDocument(HttpLoader.java:233)
	at com.apicatalog.jsonld.loader.HttpLoader.loadDocument(HttpLoader.java:193)
	at com.apicatalog.jsonld.loader.SchemeRouter.loadDocument(SchemeRouter.java:62)
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:502)
	at com.apicatalog.jsonld.context.ActiveContextBuilder.create(ActiveContextBuilder.java:174)
	at com.apicatalog.jsonld.expansion.ObjectExpansion.initLocalContext(ObjectExpansion.java:202)
	at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:101)
	at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:116)
	at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:124)
	at com.apicatalog.jsonld.processor.ToRdfProcessor.toRdf(ToRdfProcessor.java:69)
	at com.apicatalog.jsonld.api.impl.ToRdfApi.get(ToRdfApi.java:179)
	at controllers.Json2RDFServiceApp.$anonfun$json2rdf$3(Json2RDFServiceApp.scala:58)
	at scala.util.Try$.apply(Try.scala:213)
	at controllers.Json2RDFServiceApp.$anonfun$json2rdf$1(Json2RDFServiceApp.scala:46)
```

**To Reproduce**
Use HttpLoader to load a resource with no content-type header.

**Expected behavior**
JsonLdError.DOCUMENT_LOADING_ERROR should be thrown.

**Additional context**
Consider fallback if content-type is missing.

**Comment by jmvanel** [comment]
In my app, I set `MediaType.JSON_LD` on context and JSON on input,
and I keep having deterministically the same IllegalArgumentException.
Which means it works with some data, and not with others, seemingly similar, but always the same way.
Works with
http://semantic-forms.cc:1952/json2rdf?src=https://beta.grottocenter.org/api/v1/entrances/4
`IllegalArgumentException` with:
http://semantic-forms.cc:1952/json2rdf?src=https://beta.grottocenter.org/api/v1/massifs/333
The `@context` by default (context= for HTTP service) is
https://github.com/jmvanel/Karstlink-ontology/raw/master/grottocenter.org_context.jsonld
The code is here:
https://github.com/jmvanel/semantic_forms/blob/master/scala/forms_play/app/controllers/Json2RDFServiceApp.scala#L47

Titanium maybe should not demand a content type for a context `JsonDocument`, because a context, I think, should necessarily be a JSON-LD Document.
And for the input of toRdf() , I don't know if there is any difference in processing if it is JSON or JSON-LD .

**Comment by filip26** [comment]
The first issue is that your sever does not add `content-type` HTTP header to a response with a content. This issue addresses that Titanium does not expect that and fails.

**Comment by filip26** [comment]
Regarding text/plain. I'm sorry but HttpLoader cannot anticipate when text/plain means application/json. If content-type does not properly reflect the content then I would recommend to write a custom loader that wraps HttpLoader and rewrites the content-type header to the proper one.

**Comment by jmvanel** [comment]
But the point that in the first place the data source was created by `JsonDocument . of()` , so it is necessarily JSON, but  that information should not be lost in the implementation chain .

**Comment by filip26** [comment]
I'm sorry, but I don't understand. As you can see from the stacktrace HttpLoader is involved and causes the exception. Perhaps, the document you pass contains links?

**Comment by jmvanel** [comment]
The new code fixes my problem, even though the context 
https://github.com/jmvanel/Karstlink-ontology/raw/master/grottocenter.org_context.jsonld
is still the same, with text/plain Content-type .

**Comment by filip26** [comment]
You should see warnings if sl4j is configured.

e.g.
```
AVERTISSEMENT: GET on URL [http://...] does not return content-type header. Trying application/json.
```

**Comment by jmvanel** [comment]
sl4j was configured and indeed, AVERTISSEMENT is present:
`AVERTISSEMENT: GET on URL [https://ontology.uis-speleo.org/grottocenter.org_context.jsonld] does not return content-type header. Trying application/json.`

Whether this deserves a warning is a matter of taste. A JSON processor like Titanium, for the toRDF call, cannot try anything but JSON...

**Comment by filip26** [comment]
HttpLoader is used generally not by just toRdf ...

FYI:
>    The data type of the representation data is determined via the header
>   fields Content-Type and Content-Encoding.  These define a two-layer,
>   ordered encoding model:
>
>     representation-data := Content-Encoding( Content-Type( bits ) )
https://tools.ietf.org/html/rfc7231#section-3.2

and
>   In practice, resource owners do not always properly configure their
>   origin server to provide the correct Content-Type for a given
>   representation, with the result that some clients will examine a
>   payload's content and override the specified type.  Clients that do
>   so risk drawing incorrect conclusions, which might expose additional
>   security risks (e.g., "privilege escalation").  Furthermore, it is
>   impossible to determine the sender's intent by examining the data
>   format: many data formats match multiple media types that differ only
>   in processing semantics.  Implementers are encouraged to provide a
>   means of disabling such "content sniffing" when it is used.
https://tools.ietf.org/html/rfc7231#section-3.1.1.5

Missing content-type breaks one of the core HTTP principles content identification and negotiation ...

**Comment by jmvanel** [comment]
But this is interesting:
I just realize that the webmaster of the JSON data source has finally added the `@context` link inside the data, but only on one API : 
**https://beta.grottocenter.org/api/v1/massifs/333**
not on the other : 
https://beta.grottocenter.org/api/v1/entrances/4
and I forgot this.
So for the URL in bold, there are were 2 contexts for `toRdf`: one as an embedded link, and one (actually the same content but another URL) coming from Titanium by `options.setExpandContext()` .
The Titanium warning was written for the embedded link to:
https://ontology.uis-speleo.org/grottocenter.org_context.jsonld
returning non Content-Type ,
but the Expand Context URL : 
https://github.com/jmvanel/Karstlink-ontology/raw/master/grottocenter.org_context.jsonld
says:
Content-Type: text/plain

Certainly one of the 2 contexts has priority ...

**Comment by jmvanel** [comment]
OK,I'll ask my co-workers to fix the Content-Types,
but I'll use sometimes github raw URL or files for testing `@context` 's .
