### ISSUE TITLE
No setting to Skolemize blank nodes

### ISSUE THREAD

**Issue by faizaamer** [filip26/titanium-json-ld#131]
**Describe the bug**
Unable to find setting to Skolemize blank nodes as RDF4J parser allows.

**To Reproduce**
This is my input json-ld

```json
 {
   "@context": {
     "@version": 1.1,
     "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
     "xsd": "http://www.w3.org/2001/XMLSchema#",
     "et": "urn:acme:com#",
     "@vocab": "urn:acme:com#",
     "aId": {
       "@id": "@id",
       "@type": "@id"
     },
     "aVId": {
       "@id": "et:aVId",
       "@type": "@id"
     },
     "parts": {
       "@id": "et:parts",
       "@container": "@list",
       "@context": {
         "id": {
           "@id": "@id"
         }
       }
     },
     "id": {
       "@id": "et:id",
       "@type": "xsd:string"
     },
     "title": {
       "@id": "et:title",
       "@language": "en"
     },
     "type": {
       "@id": "et:type",
       "@type": "@vocab"
     },
     "version": {
       "@id": "et:version",
       "@type": "@id"
     }
   },
 
   "type": "Book",
   "title": "Title1",
   "parts": [
     {
       "version": "urn:acme:com:1111",
       "id": "urn:acme:com:2222",
       "type": "chapter",
       "title": "Chapter1"
     }
   ],
   "aId": "urn:acme:com:3333",
   "aVId": "urn:acme:com:4444"
 }
```
This is the set of triples that gets generated

```rdf
 <urn:acme:com:2222> <urn:acme:com#title> "Chapter1"@en .
 <urn:acme:com:2222> <urn:acme:com#type> <urn:acme:com#chapter> .
 <urn:acme:com:2222> <urn:acme:com#version> <urn:acme:com:1111> .
 <urn:acme:com:3333> <urn:acme:com#aVId> <urn:acme:com:4444> .
 <urn:acme:com:3333> <urn:acme:com#parts> _:genid5f5f3ab0 .
 _:genid5f5f3ab0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <urn:acme:com:2222> .
 _:genid5f5f3ab0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
 <urn:acme:com:3333> <urn:acme:com#title> "Title1"@en .
 <urn:acme:com:3333> <urn:acme:com#type> <urn:acme:com#Book> .
```

I cannot find a setting to Skolemize the blank nodes. I want to be able to create RDF4J statements to add these to remote repository using RDF4J Model api and without it I am not able to do so

**Expected behavior**
There should be an option similar to RDF4J Skolemize
https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.html#SKOLEMIZE_ORIGIN

**Additional context**

**Comment by filip26** [comment]
### Resources
* [W3C Wiki](https://www.w3.org/2011/rdf-wg/wiki/Skolemisation)
* [RDF4J Skolemization](https://github.com/eclipse/rdf4j/issues/438)

**Comment by filip26** [comment]
Hi!
The blank node id in your example (`_:genid5f5f3ab0`) is not generated by Titanium. Titanium produces blank node ids in a form `_:b[NUMBER]` e.g. `_:b0`, `_:b1` and so on. 

What is your use-case? Titanium.toRdf() -> RDF4J?

Anyway, enabling a user to set a custom blank node id generator looks like a useful enhancement.

**Comment by faizaamer** [comment]
The triples generated by Titanium parser are to be persisted using Rio.write and then loaded into a repository.

**Comment by filip26** [comment]
closed due inactivity, feel free to re-open with new information.
