### ISSUE TITLE
host Android build on maven central

### ISSUE THREAD

**Issue by CluEleSsUK** [filip26/titanium-json-ld#166]
**Is your feature request related to a problem? Please describe.**
Java 8/Android compatibility was added with https://github.com/filip26/titanium-json-ld/issues/133, but presently I can't see the jar being hosted anywhere.  

I was hoping to raise a PR on https://github.com/decentralized-identity/jsonld-common-java and https://github.com/decentralized-identity/did-common-java to provide Android support and titanium-json-ld is the key transitive dependency.

**Describe the solution you'd like**
titanium-json-ld uploaded under a separate artifactId to maven central or equivalent.

**Describe alternatives you've considered**
I've currently used git submodules to achieve the above, but it comes with problems:
- gradle doesn't have a proxy for maven profiles, so building the maven module from gradle requires a fiddly bit of groovy
- not sure if individual commits relate 1-1 to maven releases
- it's ugly

I had a look in your github actions to try and raise a PR, but it didn't seem like the maven-push action actually does a maven push and I assumed you do it manually - I could well be misunderstanding though!

**Additional context**
Thanks for your work so far!

**Comment by filip26** [comment]
Hi @CluEleSsUK,
the current `pom.xml` uses profiles to separate Java11 and Android `-Pandroid` builds, the same applies on deployment `-Pmaven-central`. Unfortunately, this approach does not allow to build and deploy both artifacts together.

I think we need to rethink this and find out the right solution. As I'm not an expert on `maven` nor `nexus-staging-maven-plugin` a help is needed and very welcome.

**Comment by CluEleSsUK** [comment]
I'm also no expert in maven or the nexus-staging plugin, but I'm happy to take a look. A cheap solution could be profiles for `-Pmaven-central` and `-Pmaven-central-android` - I'll see if I can come up with something tidier!

**Comment by filip26** [comment]
The tricky part is how to build all the artifact together. 

e.g.
```
titanium-json-ld-1.0.3.jar
titanium-json-ld-1.0.3-android.jar
titanium-json-ld-1.0.3-javadoc.jar
titanium-json-ld-1.0.3-sources.jar
titanium-json-ld-1.0.3.pom
```
Some recommend https://maven.apache.org/plugins/maven-toolchains-plugin/  to get different builds done at once, to get rid off the `android` profile.

**Comment by filip26** [comment]
The easiest solution is to name `android` artifact like `titanium-json-ld-androd' or 'titanium-android` and publish it as a separate artifact, including separate versioning, javadoc, and sources.

**Comment by pkozelka** [comment]
Yes, separate module that gets always compiled. I believe it's best; conditional compilation is rarely a good thing in Java.

**Comment by filip26** [comment]
@pkozelka  The biggest downside of this approach is that it requires two pom.xml  - one for `JRE11` build and second one for `JRE8`. Beside duplicates in the files there is no IDE support (e.g. now, you can select a maven profile in Eclipse).

What about Gradle? Could that help?

**Comment by filip26** [comment]
I've just run into toolchains.

[Guide for Supporting Multiple Versions of Java (8, 11, 14) in Your Maven Project](https://dzone.com/articles/guide-for-supporting-multiple-versions-of-java-8-1).

**Comment by filip26** [comment]
Structure:
```
pom_parent.xml
pom.xml <- default, inherits pom_parent.xml
pom_jre8.xml <- android build, inherits pom_parent.xml
```

Use `maven-flatten-plugin` to get distributable `pom`

```
> export JAVA_HOME=<JDK11>
> mvn clean package

> export JAVA_HOME=<JDK8>
> mvn -f pom_jre8.xml clean package
```
