### ISSUE TITLE
Nested @embed directive affects processing at a higher level

### ISSUE THREAD

**Issue by rybesh** [filip26/titanium-json-ld#171]
**Describe the bug**

When I create a frame with a nested `@embed` directive, it seems to affect the frame processing at a higher level, which differs from the behavior of the framing processor at the JSON-LD Playground.

**To Reproduce**

Take for example the following graph:

```jsonld
{
  "@graph": [
    {
      "@id": "http://n2t.net/ark:/39333/ncg/dataset",
      "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag",
      "member": [
        "http://n2t.net/ark:/39333/ncg/place/NCG11248",
        "http://n2t.net/ark:/39333/ncg/place/NCG07554",
        "http://n2t.net/ark:/39333/ncg/place/NCG03755"
      ]
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG03755",
      "@type": "http://n2t.net/ark:/39333/ncg/type#Mountain",
      "county": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "label": "Crawford Mountain"
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG07554",
      "@type": "http://n2t.net/ark:/39333/ncg/type#Community",
      "county": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "label": "Ichley"
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "@type": "http://n2t.net/ark:/39333/ncg/type#County",
      "label": "Orange County",
      "description": "Not to be confused with Orange County, CA"
    }
  ],
  "@context": {
    "label": {
      "@id": "http://www.w3.org/2004/02/skos/core#label"
    },
    "description": {
      "@id": "http://www.w3.org/2004/02/skos/core#note"
    },
    "county": {
      "@id": "http://n2t.net/ark:/39333/ncg/vocab#county",
      "@type": "@id"
    },
    "member": {
      "@id": "http://www.w3.org/2000/01/rdf-schema#member",
      "@type": "@id"
    }
  }
}
```

And this frame:

```jsonld
{
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@set",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  },
  "@type": "rdf:Bag",
  "records": {
    "@id": {},
    "county": {
      "@embed": "@always",
      "@explicit": true,
      "skos:label": {}
    }
  }
}
```

(See the above on the [playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fdataset%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23Bag%22%2C%22member%22%3A%5B%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%5D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Mountain%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Crawford%20Mountain%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Community%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Ichley%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23County%22%2C%22label%22%3A%22Orange%20County%22%2C%22description%22%3A%22Not%20to%20be%20confused%20with%20Orange%20County%2C%20CA%22%7D%5D%2C%22%40context%22%3A%7B%22label%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23label%22%7D%2C%22description%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23note%22%7D%2C%22county%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23county%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22member%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23member%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D&frame=%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22ncv%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23%22%2C%22nct%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23%22%2C%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22records%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22rdfs%3Amember%22%7D%2C%22county%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22ncv%3Acounty%22%7D%7D%2C%22%40type%22%3A%22rdf%3ABag%22%2C%22records%22%3A%7B%22%40id%22%3A%7B%7D%2C%22county%22%3A%7B%22%40embed%22%3A%22%40always%22%2C%22%40explicit%22%3Atrue%2C%22skos%3Alabel%22%3A%7B%7D%7D%7D%7D)).

**Expected behavior**

On the JSON-LD Playground, the above graph and frame produce these results, which are what I would expect: `county` nodes are always embedded and respecting the `@explicit` directive, but this does not affect the `records` level.

```jsonld
{
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@set",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  },
  "@id": "../dataset",
  "@type": "rdf:Bag",
  "records": [
    {
      "@id": "NCG11248",
      "@type": "nct:County",
      "county": [],
      "skos:label": "Orange County",
      "skos:note": "Not to be confused with Orange County, CA"
    },
    {
      "@id": "NCG07554",
      "@type": "nct:Community",
      "county": [
        {
          "@id": "NCG11248",
          "@type": "nct:County",
          "skos:label": "Orange County"
        }
      ],
      "skos:label": "Ichley"
    },
    {
      "@id": "NCG03755",
      "@type": "nct:Mountain",
      "county": [
        {
          "@id": "NCG11248",
          "@type": "nct:County",
          "skos:label": "Orange County"
        }
      ],
      "skos:label": "Crawford Mountain"
    }
  ]
}
```

However, using Titanium I get the following results:

```jsonld
{
    "@id": "../dataset",
    "@type": "rdf:Bag",
    "records": [
        {
            "@id": "NCG03755",
            "@type": "nct:Mountain",
            "county": [
                {
                    "@id": "NCG11248",
                    "@type": "nct:County",
                    "skos:label": "Orange County"
                }
            ],
            "skos:label": "Crawford Mountain"
        },
        {
            "@id": "NCG07554",
            "@type": "nct:Community",
            "county": [
                {
                    "@id": "NCG11248",
                    "@type": "nct:County",
                    "skos:label": "Orange County"
                }
            ],
            "skos:label": "Ichley"
        },
        "NCG11248"
    ],
    "@context": {
        "@base": "http://n2t.net/ark:/39333/ncg/place/",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
        "nct": "http://n2t.net/ark:/39333/ncg/type#",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "records": {
            "@container": "@set",
            "@type": "@id",
            "@id": "rdfs:member"
        },
        "county": {
            "@container": "@set",
            "@type": "@id",
            "@id": "ncv:county"
        }
    }
}
```

Note that the node for Orange County at the `records` level is just an `@id` reference.

**Additional context**

It seems to me that what is happening is that the `records` level is being processed with the default `"@embed": "@once"` directive, but that the embeddings at the `county` level are being counted as fulfilling that one embedding, so that at the `records` level Orange County is never embedded.

**Comment by filip26** [comment]
Hi, 
I've added the provided example as a new test and it seems to work well with `1.1.0-SNAPSHOT`. Please, could you confirm that or provide more details? Thank you

**Comment by rybesh** [comment]
I tried the latest snapshot, and got the same results. It seems that it is an issue with how I am using Titanium.

I am starting with an N-Triples file, and processing it as follows:

```java
    private static boolean frame(Path datasetPath, Path framePath) {
        try (BufferedReader datasetReader = Files.newBufferedReader(datasetPath);
                BufferedReader frameReader = Files.newBufferedReader(framePath)) {
            Document rdf = RdfDocument.of(MediaType.N_QUADS, datasetReader);
            Document jsonld = JsonDocument.of(JsonLd.fromRdf(rdf).get());
            Document jsonldFrame = JsonDocument.of(frameReader);
            JsonObject results = JsonLd.frame(jsonld, jsonldFrame).get();

            Pretty.createWriter(System.out).writeObject(results);

            return true;

        } catch (IOException | JsonLdError e) {
            return err("Failed to frame dataset using %s: %s", framePath, e);
        }
    }
```

When I do this I get the bad results described above, even with the latest snapshot. However, it works if I first use `riot` to convert my N-Triples file to a flattened JSON-LD graph, and then use the following code to do the processing:

```java
    private static boolean frame(Path datasetPath, Path framePath) {
        try (BufferedReader datasetReader = Files.newBufferedReader(datasetPath);
                BufferedReader frameReader = Files.newBufferedReader(framePath)) {
            Document jsonld = JsonDocument.of(datasetReader);
            Document jsonldFrame = JsonDocument.of(frameReader);
            JsonObject results = JsonLd.frame(jsonld, jsonldFrame).get();

            Pretty.createWriter(System.out).writeObject(results);

            return true;

        } catch (IOException | JsonLdError e) {
            return err("Failed to frame dataset using %s: %s", framePath, e);
        }
    }
```

Am I not converting from N-Triples to JSON-LD correctly?

**Comment by filip26** [comment]
It looks like there is a bug in N-Triples parser or/and in fromRdf implementation. Can you share the N-Triples input file or check  if the intermediary result after `JsonLd.fromRdf(rdf).get()` is correct?

**Comment by rybesh** [comment]
Here's a zip with the N-Triples file and the JSON-LD that `fromRdf` produced. Looks like it is missing the `"@graph" : []` around all the graph nodes.

[Archive.zip](https://github.com/filip26/titanium-json-ld/files/6579768/Archive.zip)

**Comment by filip26** [comment]
That's interesting. 'fromRdf' uses `@graph` to denote named graphs. In that case `@graph` is paired with `@id` representing the graph IRI. Not sure why `frame` fails without it, yet.

Quick workaround, for now, could be to add `@graph: []` manually.

**Comment by rybesh** [comment]
I still get the same problematic output even if I manually add the `@graph: []`.

Graph:
```jsonld
{
  "@graph": [
    {
      "@id": "http://n2t.net/ark:/39333/ncg/dataset",
      "@type": [
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag"
      ],
      "http://www.w3.org/2000/01/rdf-schema#member": [
        {
          "@id": "http://n2t.net/ark:/39333/ncg/place/NCG03755"
        },
        {
          "@id": "http://n2t.net/ark:/39333/ncg/place/NCG07554"
        },
        {
          "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248"
        }
      ]
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG03755",
      "http://n2t.net/ark:/39333/ncg/vocab#county": [
        {
          "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248"
        }
      ],
      "@type": [
        "http://n2t.net/ark:/39333/ncg/type#Mountain"
      ],
      "http://www.w3.org/2004/02/skos/core#label": [
        {
          "@value": "Crawford Mountain"
        }
      ]
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG07554",
      "http://n2t.net/ark:/39333/ncg/vocab#county": [
        {
          "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248"
        }
      ],
      "@type": [
        "http://n2t.net/ark:/39333/ncg/type#Community"
      ],
      "http://www.w3.org/2004/02/skos/core#label": [
        {
          "@value": "Ichley"
        }
      ]
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "@type": [
        "http://n2t.net/ark:/39333/ncg/type#County"
      ],
      "http://www.w3.org/2004/02/skos/core#label": [
        {
          "@value": "Orange County"
        }
      ],
      "http://www.w3.org/2004/02/skos/core#note": [
        {
          "@value": "Not to be confused with Orange County, CA"
        }
      ]
    }
  ]
}
```

Frame:
```jsonld
{
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@set",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  },
  "@type": "rdf:Bag",
  "records": {
    "@id": {},
    "county": {
      "@embed": "@always",
      "@explicit": true,
      "skos:label": {}
    }
  }
}
```

Result:
```jsonld
{
  "@id": "../dataset",
  "@type": "rdf:Bag",
  "records": [
    {
      "@id": "NCG03755",
      "@type": "nct:Mountain",
      "county": [
        {
          "@id": "NCG11248",
          "@type": "nct:County",
          "skos:label": "Orange County"
        }
      ],
      "skos:label": "Crawford Mountain"
    },
    {
      "@id": "NCG07554",
      "@type": "nct:Community",
      "county": [
        {
          "@id": "NCG11248",
          "@type": "nct:County",
          "skos:label": "Orange County"
        }
      ],
      "skos:label": "Ichley"
    },
    "NCG11248"
  ],
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@set",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  }
}
```

**Comment by filip26** [comment]
The missing `@graph` it not the issue but members order.  if 

```json
        {
          "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248"
        }
```
is the first item in `member` array, as in your first example, then it works as expected.  btw. json-ld-playground produces the same result as Titanium. see [here](https://tinyurl.com/y3xpyaf6)

**Comment by rybesh** [comment]
Ah, I see. That makes sense. Adding `"@embed": "@always"` under `records` seems to give me the results I want. Though what I *really* want is to have `records` as an id map; see #172.
