### ISSUE TITLE
Support xsd:int type coercion

### ISSUE THREAD

**Issue by ebremer** [filip26/titanium-json-ld#178]
**Describe the bug**
Using titanium 1.1.0, importing triples with, RdfDocument.of with setUseNativeTypes to true is being ignored.

**To Reproduce**
_:B58e8ccf8X2D76bcX2D46caX2D9912X2Dec48f4fe6d83 <http://iiif.io/api/image/2#height> "4652"^^<http://www.w3.org/2001/XMLSchema#int> .
_:B58e8ccf8X2D76bcX2D46caX2D9912X2Dec48f4fe6d83 <http://iiif.io/api/image/2#width> "6324"^^<http://www.w3.org/2001/XMLSchema#int> .

with above yields:
        "http://iiif.io/api/image/2#height": [
            {
                "@value": "4652",
                "@type": "http://www.w3.org/2001/XMLSchema#int"
            }
        ],
        "http://iiif.io/api/image/2#width": [
            {
                "@value": "6324",
                "@type": "http://www.w3.org/2001/XMLSchema#int"
            }
        ]
**Expected behavior**
should have yielded:
        "http://iiif.io/api/image/2#height": 4652,
        "http://iiif.io/api/image/2#width": "6324"

**Comment by filip26** [comment]
Hi,
thank you for reporting that.`xsd:int` is not supported now as the spec lists only `xsd:boolean`, `xsd:double`, `xsd:string` and `xsd:integer`. 

TODO
 * print warning about an unsupported XSD type
 * implement `xsd:int` support (signed 32-bit integer)

**Comment by ebremer** [comment]
The specification listed at https://www.w3.org/TR/json-ld11/, says "...all other numbers are interpreted as typed values with type xsd:integer".  As no specific number types are listed, I would think it would be safe to assume that long, int, short, byte, nonNegativeInteger, etc, which are all subclassed from integer, could be supported without breaking any rules.
