### ISSUE TITLE
Expose the prefixes found in the top level @context, including remote @context.

### ISSUE THREAD

**Issue by afs** [filip26/titanium-json-ld#193]
Prefixes have no standing in the RDF data model but they are convenient for display of URIs.

**Describe the solution you'd like**
Expose the compact URI prefix mapping from the top-level `@context`, maybe a method `RdfDataset.prefixes()` that returns a 
`Map<String, String>`. This would be limited to the prefixes from the top level `@context`, the active context in-scope at the end of parsing the top level JSON after any nested local context have dropped out-of-scope.

**Describe alternatives you've considered**
Secondary parsing at the JSON level of the JSON Document (this is what Jena v4.2.0 does). This does not included remote `@context` as it would require re-downloading the URL or interacting with any context cache.

Jena also requires the prefix URI to end in "/", "#" or ":" and Jena includes `@vocab` as prefix "". There are pragmatic Jena decisions that could be applied to the `Map` returned by Titanium.

**Additional context**
This came up as part of [JENA-2187](https://issues.apache.org/jira/browse/JENA-2187).

**Comment by filip26** [comment]
How to deal with conflicting prefixes? 

e.g.
```json
{
  "@context": {
    "name": "http://example.com/person#name",
    "details": "http://example.com/person#details"
  },
  "name": "Markus Lanthaler",
  "details": {
    "@context": {
      "name": "http://example.com/organization#name"
    },
    "name": "Graz University of Technology"
  }
}
```
converted into n-quads
```
_:b0 <http://example.com/person#details> _:b1 .
_:b0 <http://example.com/person#name> "Markus Lanthaler" .
_:b1 <http://example.com/organization#name> "Graz University of Technology" .
```
What should contain the prefix map?

**Comment by afs** [comment]
`"name": "http://example.com/person#name"` isn't really a prefix - it's a short name for a URI. 
Prefixes appear in Turtle as `prefix:localName` which is more like:
`"person": "http://example.com/person#"` and then `person:name`

Those can be nested as well so there is a decision point here.
There isn't a wrong answer.

RDF/XML can have nested xml namespaces declarations (the XML equivalent of prefixes). It is quite unusual to see nested XML namespaces in RDF/XML - I think they would be more common in JSON-LD. 

JSON is slightly different to XML because XML is parsed in encounter order and JSON is a map.

Possibility 1: ignoring the inner `@context` and only expose the document-wide declarations.
Possibility 2: slightly more complicated is "put in as nested - outer overrides inner"

It  probably makes sense for the outer, document definition to be in the final outcome.

HTH

**Comment by filip26** [comment]
if  the given example should produce prefix map like this one:
```json
{ 
  "person":  "http://example.com/person#", 
  "organization":  "http://example.com/organization#",
}
```
then we have to develop an algorithm for extracting and naming prefixes from JSON-LD context. Perhaps, we could start with a map of well known prefixes (foaf, skos, ...).

**Comment by filip26** [comment]
Just an aside note: from another point of view; as I understand prefixes are about readability. Thus in some cases it would be more beneficial to the consumer of an output to provide its own list of well known prefixes in order to get an easily readable output.

**Comment by afs** [comment]
Yes. The user can add them to the Jena graph for example, or even read a Turtle file which only has prefixes. This happens when loading N-triples - no prefixes, but common for large database dumps - and the user wants to get some nicer output.

**Comment by filip26** [comment]
I'm preparing low level JsonLdProcessor that will allow to grab a context or/and optimize processing. Target version is 1.3.0

**Comment by afs** [comment]
Sad to hear that v2 is cancelled.

**Comment by filip26** [comment]
@afs I'm sorry, but I have no other choice. I hear Titanium has millions production installations in total from various companies, but none is willing to pay a few bugs back.

**Comment by hmottestad** [comment]
I'm also sorry to hear that v2 has been canceled.
