### ISSUE TITLE
Issue with framing (flattening) and @reverse in @context.

### ISSUE THREAD

**Issue by gnoric** [filip26/titanium-json-ld#198]
**Describe the bug**
When using @reverse in a top level property context, lower node's relations are created to that root node, not their parent node. This issue can already be seen after flattening occurs so framing context is not required, however it has been added here to explain the full process.

**To Reproduce**

**JSONLD**
can be loaded from [http://adidas.devxt.de/example/dev.short.json]
<pre>
{
  "@context" : "http://adidas.devxt.de/example/dev.short.context.json",
  "data": {
    "allFactSheets": {
      "edges": [
        {
          "node": {
            "id": "ec254751-86be-4b7d-82b8-b716bedb87ce",
            "displayName": "#MYBEST",
            "type": "Application",
            "qualitySeal": "APPROVED",
            "relApplicationToDataObject": {
              "edges": [
                {
                  "node": {
                    "type": "RelApplicationToDataObject",
                    "id": "9a8fb137-0a53-4c95-adbb-d9f8bd27b2bc",
                    "factSheet": {
                      "id": "338b1d1d-617d-4ee4-b79f-dee72e265831",
                      "displayName": "IT Landscape Meta Data",
                      "type": "DataObject"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  },
  "errors": null
}
</pre>

**Context**
can be loaded from [http://adidas.devxt.de/example/dev.short.context.json]
<pre>
{
  "@context":{
    "@base":"http://leanix.net/",
    "col":"https://adidas-dev.collibra.com/",
    "type":"@type",
    "id":"@id",
    "data":"col:ignore",
    "allFactSheets":{
      "@reverse":"col:assets_in_domain_relation",
      "@container":"@index"
    },
    "edges":"@nest",
    "displayName":{
      "@id":"col:displayname",
      "@type":"xsd:string"
    },

    "DataObject":"col:00000000-0000-0000-0000-000000031026",

    "node" : "@nest",
    "relApplicationToDataObject" : {
      "@id" : "col:relates",
      "@container" : "@index",
      "@context" : {
        "factSheet" : "col:to",
        "RelApplicationToDataObject" : "col:1099a85a-48c4-4d34-996e-07f63bc0034e"
      }   
    }
  }
}
</pre>

**Frame**
Can be loaded from [http://adidas.devxt.de/example/dev.short.frame.json]. Frame is not needed for understanding the issue, as it happens during the flattening (e.g. when using an empty frame)
```json
{
  "@context":{
    "@base":"http://leanix.net/",
    "col":"https://adidas-dev.collibra.com/",
    "type":"@type",
    "id":"@id",
    "data":"col:ignore",
    "allFactSheets":{
      "@reverse":"col:assets_in_domain_relation"
    },
    "displayName":{
      "@id":"col:displayname",
      "@type":"xsd:string"
    },
    
    "DataObject":"col:00000000-0000-0000-0000-000000031026",
    
    "relation" : "col:relates",
    "from" : "col:from",
    "to" : "col:to"
  },
  "data":{
    "type" : {"@default" : "col:2cc7d681-42bd-4a1d-ab85-7b5386f0c71a"},
    "allFactSheets":{}
  }
}
```
**Expected behavior**
As viewable [in the playground](https://json-ld.org/playground/#startTab=tab-flattened&json-ld=http%3A%2F%2Fadidas.devxt.de%2Fexample%2Fdev.short.json&context=%7B%7D). Important parts are **bold**.

<pre>
{
  "@graph": [
    {
      "@id": "_:b0",
      "https://adidas-dev.collibra.com/ignore": {
        "@id": "_:b1"
      }
    },
    {
      "@id": "http://leanix.net/338b1d1d-617d-4ee4-b79f-dee72e265831",
      "@type": "https://adidas-dev.collibra.com/00000000-0000-0000-0000-000000031026",
      "https://adidas-dev.collibra.com/displayname": {
        "@type": "xsd:string",
        "@value": "IT Landscape Meta Data"
      }
    },
    {
      "@id": "http://leanix.net/9a8fb137-0a53-4c95-adbb-d9f8bd27b2bc",
      "@index": "edges",
      "@type": "https://adidas-dev.collibra.com/1099a85a-48c4-4d34-996e-07f63bc0034e",
      <b style="color:green">"https://adidas-dev.collibra.com/to": {
        "@id": "http://leanix.net/338b1d1d-617d-4ee4-b79f-dee72e265831"
      }</b>
    },
    {
      "@id": "http://leanix.net/ec254751-86be-4b7d-82b8-b716bedb87ce",
      "@index": "edges",
      "@type": "http://leanix.net/Application",
      "https://adidas-dev.collibra.com/assets_in_domain_relation": {
        "@id": "_:b1"
      },
      "https://adidas-dev.collibra.com/displayname": {
        "@type": "xsd:string",
        "@value": "#MYBEST"
      },
      <b>"https://adidas-dev.collibra.com/relates": {
        "@id": "http://leanix.net/9a8fb137-0a53-4c95-adbb-d9f8bd27b2bc"
      }</b>
    }
  ]
}
</pre>

**Titanium behavior**
Important parts are **bold**.

<pre>
{
    "@graph": [
        {
            "https://adidas-dev.collibra.com/ignore": {
                "@id": "_:b1"
            }
        },
        {
            "@id": "_:b1"
        },
        {
            "@id": "http://leanix.net/338b1d1d-617d-4ee4-b79f-dee72e265831",
            "@type": "https://adidas-dev.collibra.com/00000000-0000-0000-0000-000000031026",
            "https://adidas-dev.collibra.com/displayname": {
                "@type": "xsd:string",
                "@value": "IT Landscape Meta Data"
            },
            <b>"https://adidas-dev.collibra.com/to": {
                "@id": "_:b1"
	   }</b>
        },
        {
            "@id": "http://leanix.net/9a8fb137-0a53-4c95-adbb-d9f8bd27b2bc",
            "@index": "edges",
            "@type": "https://adidas-dev.collibra.com/1099a85a-48c4-4d34-996e-07f63bc0034e",
	    <b>"https://adidas-dev.collibra.com/relates": {
                "@id": "_:b1"
            }</b>
        },
        {
            "@id": "http://leanix.net/ec254751-86be-4b7d-82b8-b716bedb87ce",
            "@index": "edges",
            "@type": "http://leanix.net/Application",
            "https://adidas-dev.collibra.com/assets_in_domain_relation": {
                "@id": "_:b1"
            },
            "https://adidas-dev.collibra.com/displayname": {
                "@type": "xsd:string",
                "@value": "#MYBEST"
            }
        }
    ]
}
</pre>

**Expected behavior**
The relations should be resolved correctly, to the parent node, not to the root of the  @reversed property.

**Additional context**
The sample is a subset of in-use data. We receive the data in that specific format and have no way to preformat it. Resolving in playground seems to work fine. 

**Main questions**

- Is there any workaround to get titanium to work as playground / spec?
- Is there a chance that this can be fixed with priority?

Please let me know if anything is unclear. Thank you for your work!

**Comment by filip26** [comment]
Hi @gnoric ,
thank you for reporting the issue. Should be fixed by PR #199. Please feel to re-open.

There is no public JSON-LD playground using titanium as an engine. Good idea!
