### ISSUE TITLE
benchmark titanium against jsonld-java

### ISSUE THREAD

**Issue by VladimirAlexiev** [filip26/titanium-json-ld#209]
Hi @filip26 !
Thanks for your implementation! 
There's a good chance it'll replace `jsonld-java` in rdf4j, one of the most important java rdf frameworks: https://github.com/eclipse/rdf4j/issues/3654.

However, @umbreak did some benchmarking 11m ago showing your implementation to be 10x slower than `jsonld-java`: https://github.com/umbreak/jsonld-benchmarks.

He guessed in https://github.com/jsonld-java/jsonld-java/pull/284#issuecomment-788154368 that this may be due to 1.1 features, but @gkellogg countered there should be almost no slowdown for 1.0 files.

Would it be possible for you to repeat the benchmark, and if confirmed, to think about some ways of speeding up your implementation? Ontotext may be able to contribute to these tasks, depending on developments in client projects.

Thanks in advance!

**Comment by filip26** [comment]
Hi @VladimirAlexiev 
the benchmark shows that 1.1 implementation/algorithm is slower than 1.0 implementation as there is no other JSON-LD 1.1 processor in Java, as far as I know.

All PRs are welcome, especially those improving performance. 

BTW. there is another open issue #184 on performance.

**Comment by umbreak** [comment]
Hi. I was the one doing the benchmark. As I mentioned in the README, I just took a subset of the benchmarks from [W3C](W3C compliance test suite for JSON-LD 1.1) that did work for both JSON-LD java (which only supports partially 1.1) and Titanium.

I can try running them again once I have a little bit of free time. I think just bumping dependencies should be enough.

**Comment by umbreak** [comment]
There has been a good progress on the Titanium side. 
Right now the difference on the tests I've run between Json-LD Java and Titanium are not ~ x10x in favour of Json-LD Java, but ~ 5x. [Find the updated results in my repo](https://github.com/umbreak/jsonld-benchmarks)

**Comment by filip26** [comment]
@umbreak thank you for the benchmark!

I'm closing this issue as there is an older one (#184).  Please, let's move there.

**Comment by filip26** [comment]
Please check the latest v2 milestones. Performance has improved significantly. Feedback and contributions on v2 are welcome.
