### ISSUE TITLE
How to load multiple contexts from local reference

### ISSUE THREAD

**Issue by SethiShivam** [filip26/titanium-json-ld#235]
Hi Team , I am trying to develop the normalize functionality to Normalize the proof and it requires to access the environment .

But I want to achieve this without using internet , due to securities issue ,

Could someone please help me with how to load the  multiple contexts (may be in array) from local storage rather than calling the context url again and again . 
I think JSON documentloader could help me with this , but I didn't find any proper documentation.

Best Regards
Sethi Shivam

**Comment by filip26** [comment]
Hi,
`file` scheme is supported out of the box. e.g. `file:///home/....` or implement your own [DocumentLoader](https://javadoc.io/doc/com.apicatalog/titanium-json-ld/latest/com/apicatalog/jsonld/loader/DocumentLoader.html). 

See an example here https://github.com/filip26/iron-verifiable-credentials/blob/main/src/main/java/com/apicatalog/vc/loader/StaticContextLoader.java

btw. this is not the right place where to ask for free help.
