### ISSUE TITLE
Some URI resources are resolving as strings rather than URI

### ISSUE THREAD

**Issue by ebremer** [filip26/titanium-json-ld#237]
**Describe the bug**
Running:
https://github.com/ebremer/jenabug/blob/master/src/main/java/com/demo/Titanium2a.java
will read in a small amount of schema.org data from a json-ld file.  URI (whether absolute or relative) are being interpreted as strings rather than URIs even though some of the fragments are listed explicitly as URIs elsewhere in the jsonld file.

**To Reproduce**
run: https://github.com/ebremer/jenabug/blob/master/src/main/java/com/demo/Titanium2a.java

**Expected behavior**
relative URIs should be resolved and URIs to URIs instead of Strings.

**Comment by filip26** [comment]
Hi, please provide more details, especially a snipped of the data that is not interpreted as expected would be useful. 

JSON-LD test suite defines a lot of tests related to expanding relative IRIs see [Transform JSON-LD to RDF](https://w3c.github.io/json-ld-api/tests/toRdf-manifest.html) that are all passed.

**Comment by ebremer** [comment]
I fixed the issue by wrapping the IRI strings with {"@id": "relativepath/subfolder"} and it is working fine now.  I didn't realize I was getting by earlier on coercion rules that were specified in the context.
