### ISSUE TITLE
Provide a multi-release jar?

### ISSUE THREAD

**Issue by laeubi** [filip26/titanium-json-ld#238]
**Is your feature request related to a problem? Please describe.**
Currently there are two jar build, one for java 8 and one for java 11

**Describe the solution you'd like**
[JEP 238](https://openjdk.org/jeps/238) defines a way to build a single jar that can contain code for java 8 and any version 9+ in the same jar.

**Additional context**
Having only one dependency will likely simplify build (only one pom) and usage (java 11 code is automatically used when running on a suitable vm).

**Comment by filip26** [comment]
Hi @laeubi, thank you for sharing JEP 238. I've been looking for something like that for a long time.

**Comment by laeubi** [comment]
The maven setup is a bit cumbersome, but if you like you can find an example here: https://github.com/ClickHouse/clickhouse-jdbc/blob/f285b73d45597e29cf36dff4daf4cb4f9f53453a/pom.xml#L498-L532

**Comment by filip26** [comment]
thanks, that looks promising, I see it uses `jdkToolchain`. I wonder how to build it with using Github Actions.

**Comment by filip26** [comment]
#166

**Comment by laeubi** [comment]
> I wonder how to build it using Github Actions.

You can vote for https://github.com/actions/setup-java/issues/276

You can add a static one e.g. like this
https://github.com/eclipse-platform/eclipse.platform/blob/master/.github/toolchains.xml

and pass it to the maven build:
https://github.com/eclipse-platform/eclipse.platform/blob/4d2af8c7770d66a025f349513b5fe9f379a2630b/.github/workflows/build.yml#L31

but I have also seen generate it on the fly...

**Comment by laeubi** [comment]
@filip26 is there any schedule for this already? Once this is done I'd like to propose a patch on this to add OSGi meta-infos, so would be nice to hear if it makes sense to wait for this or better do the work twice in the old infrastructure.

**Comment by filip26** [comment]
Hi @laeubi ,
I'm sorry, but I cannot set a date. Titanium is an open-source project and no one gets paid to work on it., It could be a week or a few months.

**Comment by laeubi** [comment]
Alright, let me know if I can help with anything.

**Comment by filip26** [comment]
Well, I'm happy to accept any PR that is in benefit of the library users ;)

**Comment by filip26** [comment]
add a resource [Multi-release JARs - Good or bad idea?](https://blog.gradle.org/mrjars)

**Comment by laeubi** [comment]
Well that is more than five years ago now and I see MJARS in the wild (e.g. gson)... beside that its not the responsibility of a library to overcome possibly limitations of tools (gradle?), but for sure it is your choice in the end :-)

**Comment by filip26** [comment]
thank you for the reaction. The only motivation to provide JRE8 build is Android development for which Gradle is preferred over Maven. Do you have an experience with MJARS on Android?

**Comment by laeubi** [comment]
No, but as MJARs (from Java/Android POV) are just jars with a few extra bytes I won't expect anything worse here and any Java ) compliant JVM should support MJARs at the runtime.

**Comment by filip26** [comment]
closed due inactivity, feel free to re-open with new information.
