### ISSUE TITLE
Allow to set custom DocumentResolver

### ISSUE THREAD

**Issue by filip26** [filip26/titanium-json-ld#239]
**Is your feature request related to a problem? Please describe.**
`HttpLoader` can load only RDF and JSON-LD documents.

**Describe the solution you'd like**
Allow to set custom `DocumentResolver` enabling custom document loading.

**Describe alternatives you've considered**
Default `DocumentResolver` could be exposed and configurable.

**Comment by skodapetr** [comment]
`DocumentResolver` is used in the `DefaultHttpLoader`, `FileLoader`, and `ZipResourceLoader`.
Those are created before the `JsonLdOptions` object, as a result, we can no directly set `resolver` using `JsonLdOptions`.

We could: 
- Split `DocumentResolver` into interface and `DefaultDocumentResolver`.
- Add constructor to Loaders which would allow to set custom `resolver`.
That would allow users to provide custom implementation with the added cost of manual `SchemeRouter` constrcution.

**Comment by filip26** [comment]
V2 has been canceled because of lack of funding.
