### ISSUE TITLE
Usage of @reverse breaks scoped contexts

### ISSUE THREAD

**Issue by jakubklimek** [filip26/titanium-json-ld#248]
**Describe the bug**
Usage of `@reverse` instead of `@id` prevents parts of scoped context from being interpreted.

**To Reproduce**
Parse this json-ld file as RDF, e.g. through Apache Jena (tested on 4.7.0) and Titanium in LinkedPipes ETL using titanium-json-ld 1.3.1:
```json
{
  "@context": {
    "@version": 1.1,
    "@base": "https://test",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "item": {
      "@id": "https://item",
      "@context": {
        "title": {
          "@id": "https://title",
          "@container": "@language"
        },
        "subitems": {
          "@reverse": "https://subitem-of",
          "@context": {
            "subitem": {
              "@id": "https://subitem",
              "@context": {
                "title": {
                  "@id": "https://title",
                  "@container": "@language"
                },
                "description": {
                  "@id": "https://description",
                  "@container": "@language"
                }
              }
            }
          }
        }
      }
    }
  },
  "@graph": [{
    "@id": "item1",
    "@type": "item",
    "subitems": [{
      "@id": "subitem1",
      "@type": "subitem",
      "title": {
        "cs": "title"
      },
      "description": {
        "cs": "description"
      }
  }]
}]
}
```
The resulting RDF triples are - note the missing title and description:
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://test/item1>  a  <https://item> .

<https://test/subitem1>
        a                     <https://test/subitem> ;
        <https://subitem-of>  <https://test/item1> .
```

**Expected behavior**
When the same file with `@reverse` is transformed in JSON-LD playground, the result is:
```turtle
<https://test/item1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://item> .
<https://test/subitem1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://subitem> .
<https://test/subitem1> <https://description> "description"@cs .
<https://test/subitem1> <https://subitem-of> <https://test/item1> .
<https://test/subitem1> <https://title> "title"@cs .
```

**Additional context**
When I switch `@reverse` to `@id` and use titanium, I get the title and description OK:
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://test/item1>  a       <https://item> ;
        <https://subitem-of>  <https://test/subitem1> .

<https://test/subitem1>
        a                      <https://subitem> ;
        <https://description>  "description"@cs ;
        <https://title>        "title"@cs .
```

**Comment by filip26** [comment]
could be related to https://github.com/w3c/json-ld-api/issues/565

**Comment by skodapetr** [comment]
@filip26  What is you position on this issue?

They updated the Editor draft in reaction to https://github.com/w3c/json-ld-api/issues/565, dropping the "return" from 13.7 at https://www.w3.org/TR/json-ld11-api/#create-term-definition. Yet the change remains only in the editor draft. In the [associated PR](https://github.com/niklasl/json-ld-api/commit/f6c7a2aceb2ee85999d3668f331f6dca2e92045d). they also added a new test. Is there a chance to support also the Editors draft in titanium-json-ld, or do you strictly adhere to the last Recommendation?

Also, just dropping the return statement from the [TermDefinitionBuidler](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/jsonld/context/TermDefinitionBuilder.java#L345) is not a solution on its own as it causes (`JsonLdError[code=The local context defined within a term definition is invalid [code=INVALID_SCOPED_CONTEXT].`)

**Comment by filip26** [comment]
@skodapetr if the change does not break existing tests then let's do that. Thank you

**Comment by skodapetr** [comment]
@filip26 Yes, there is a new test in the expansion section associated with the PR. I think this new test should be also included in titanium-json-ld tests. If you agree can you hint preferred way? The tests are part of a zip file with date, should we replace this file with the new content and current date?

**Comment by filip26** [comment]
@skodapetr great, I'll sync the `json-ld-test-suite-[timestamp].zip`. It's made with pom.xml and maven and then the resulting `jar` is renamed to `zip` then.

**Comment by filip26** [comment]
@skodapetr please sync with branch https://github.com/filip26/titanium-json-ld/tree/patch/issue-311 two new tests are failing.
