### ISSUE TITLE
Frame aliasing `@graph` broken when `omitGraph = false`

### ISSUE THREAD

**Issue by lolgab** [filip26/titanium-json-ld#257]
**Describe the bug**
I want to rename the `@graph` name to something like `data` to have a Json output which can be consumed by applications that are not aware of Linked Data. This doesn't seem to work on titanium-json-ld

**To Reproduce**
Given this frame:
```json
{
  "@context": {
    "data": "@graph"
  }
}
```

and this Json-LD:
```json
{
  "@graph": [
    {
      "@id": "http://example.org/foo",
      "http://example.org/name": "Foo"
    },
    {
      "@id": "http://example.org/bar",
      "http://example.org/name": "Bar"
    }
  ]
}
```

Framing with the `omitGraph = false` option returns:

```json
{
  "@graph": [
    {
      "data": [
        {
          "@id": "http://example.org/foo",
          "http://example.org/name": "Foo"
        },
        {
          "@id": "http://example.org/bar",
          "http://example.org/name": "Bar"
        }
      ]
    }
  ],
  "@context": {
    "data": "@graph"
  }
}
```

Where the JSON-LD Playground returns:
```json
{
  "@context": {
    "data": "@graph"
  },
  "data": [
    {
      "@id": "http://example.org/bar",
      "http://example.org/name": "Bar"
    },
    {
      "@id": "http://example.org/foo",
      "http://example.org/name": "Foo"
    }
  ]
}
```

**Expected behavior**
My expectation is to have the same result as JSON-LD Playground

```json
{
  "@context": {
    "data": "@graph"
  },
  "data": [
    {
      "@id": "http://example.org/bar",
      "http://example.org/name": "Bar"
    },
    {
      "@id": "http://example.org/foo",
      "http://example.org/name": "Foo"
    }
  ]
}
```

**Comment by lolgab** [comment]
@filip26 do you have any idea why this happens and what is needed to fix it? I could try to open a PR.
The official w3c test suite doesn't cover this use case, but from the specification it seems to be supported. Do you know if my expectation is correct in first place? Thank you!

**Comment by filip26** [comment]
@lolgab the spec allows to alias any keyword except `@context`.The first step is to create a test case. 
Please note, framing algorithm processes an input + frame in an expanded form. [see line 116 and 119](https://github.com/filip26/titanium-json-ld/blob/a54af410198c2ef101f4c081711b8c79f3189985/src/main/java/com/apicatalog/jsonld/processor/FramingProcessor.java#L116). If the result of expansion is correct then there could be bug in the framing algorithm implementation.

**Comment by lolgab** [comment]
I managed to reproduce the error in tests and fix it :)

**Comment by filip26** [comment]
@lolgab excellent, thank you! Please check the second test case, see my comment on PR.
