### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by hmottestad** [filip26/titanium-json-ld#273]
**Is your feature request related to a problem? Please describe.**
Need to measure the performance of the library.

**Describe the solution you'd like**
JMH benchmarks with as realistic data as possible.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/filip26/titanium-json-ld/pull/272
https://github.com/umbreak/jsonld-benchmarks/issues/3

**Comment by filip26** [comment]
V2 has been canceled because of lack of funding.
