### ISSUE TITLE
Force HTTPS on HttpLoader

### ISSUE THREAD

**Issue by filip26** [filip26/titanium-json-ld#297]
**Is your feature request related to a problem? Please describe.**
`HttpLoader` does not distinguish between `http` and `https`. 

**Describe the solution you'd like**
```javascript
HtttpLoader.defaultInstance().httpsOnly()
```
**Describe alternatives you've considered**
Wrapping custom `DocumentLoader` enforcer. e.g. `SchemeRouter`

**Comment by skodapetr** [comment]
Could we just remove "http" from [SchemaRouter](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/jsonld/loader/SchemeRouter.java#L30) to get the same effect, that is to disable http?

**Comment by filip26** [comment]
@skodapetr that's not the same as allowing to enforce it. e.g. You can pass `DefaultHttpLoader` directly as a document loader, no need to wrap into `SchemaRouter` if you don't intend to support more protocols.

**Comment by skodapetr** [comment]
So the idea is to add a "switch" `httpsOnly`  to `DefaultHttpLoader`. When switch on, every http request is replaced with https request. Is that correct?

Should there be a method to turn this back off?

**Comment by filip26** [comment]
> So the idea is to add a "switch" httpsOnly to DefaultHttpLoader. When switch on, every http request is replaced with https request. Is that correct?

that's one option, I'm thinking about extending HttpClient interface of a new getter/setter. 
```javascript
 setHttpPolicy(Optional|Required|Enforced);
```
Optional - same as now, both `http` and `https` get through
Required - `http` requests are rejected, an exception is thrown
Enforced - `http` requests are rewritten to `https`

**Comment by filip26** [comment]
V2 has been canceled because of lack of funding.
