### ISSUE TITLE
Add support to create RDF* statements

### ISSUE THREAD

**Issue by pajoma** [filip26/titanium-json-ld#305]
**Is your feature request related to a problem? Please describe.**
I am using RDF4J as backend with RDF* statements in the form 

`<triple> predicate value`. 

I am unable to convert these statements in RDFNQuads, since the subject is expected to be a RdfResource

**Describe the solution you'd like**
The RdfTriple interface could extend the RdfResource ([example from RDF4J](https://github.com/eclipse-rdf4j/rdf4j/blob/main/core/model-api/src/main/java/org/eclipse/rdf4j/model/Triple.java)), to create RDFNQuads with RDF* semantics. 

**Describe alternatives you've considered**
Not sure, for now I am filtering all RDF* statements.

**Comment by filip26** [comment]
@pajoma I'm sorry, but this project has nothing to do with RDF4J. Report the bug to RDF4J. Please feel free to re-open if there is something I'm missing.

**Comment by pajoma** [comment]
Sorry for the confusion, I just mentioned RDF4J as example. 

The problem lies within the RDF Api of Titanium (RDFNQuads and Rdf Resource are Titanium Terms, nothing related to RDF4J)

**Comment by filip26** [comment]
Please, can you be more specific then?  Why you cannot use the existing RDF API? `RdfNQuad` just extends `RdfTriple` of graph name which can be `null`.

**Comment by pajoma** [comment]
Sure. 

RDF statements are triples in the form `<subject> <predicate> <object>`. 
RDF quads include the context: `<subject> <predicate> <object> <graph>`. 

RDF* allows for expressing statements about statements (in subjects or objects): 

` <<subject> <predicate> <object>> <predicate> <object>` or
` <subject> <predicate> <<subject> <predicate> <object>>`  

A valid triple (let's forget about the graph for now) is therefore: 
`<Resource> <IRI> <Value>` with
* Resource being either a blank node, an IRI or a triple (RDF*)
* Value being either a blank node, an IRI, a triple or a literal

You typically see this reflected in the class hierarchy, see [RDFLib](https://rdflib.readthedocs.io/en/stable/rdf_terms.html), [Eclipse RDF4J](https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/model/Value.html) or [Apache Jena](https://www.javadoc.io/doc/org.apache.jena/jena-core/latest/org.apache.jena.core/org/apache/jena/rdf/model/RDFNode.html)

In my application, I want to expose my triples as JSON-LD documents with RDF-Star statements. The implementation follows this pattern: 


for each statement in the result model: 
1.  convert the subject into a [RdfResource](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/rdf/RdfResource.java)
2. convert the object into a [RdfValue](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/rdf/RdfValue.java)
3. create a new RDFNQuad
4. Add it to the new RdfDataset

And then I build a JsonLd Document

```java
Document document = RdfDocument.of(myRdfDataset);
JsonArray jsonValues = JsonLd.fromRdf(document).options(myOptions).get();
JsonDocument jsonDocument = JsonDocument.of(jsonValues);
JsonObject jsonObject = JsonLd.frame(jsonDocument, myContectUri).options(myOptions).get();
```

*The issue*: 
The [RdfTriple ](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/rdf/RdfTriple.java) class expects a RdfResource as subject (and a RdfValue as object). Since RDF* requires triples as subjects and objects, the Triple itself should be a RdfResource itself again. 

I would expect the following class structure: 

* RdfValue
  * RdfLiteral
  * RdfResource
     * RdfTriple
       * RdfNQuad

Only then is it possible to create a new RDFNQuad with a triple either as subject or object (this should also include a check that it is actually a triple, and not another nquad)

**Comment by filip26** [comment]
should be done after/together with/ #300

**Comment by filip26** [comment]
V2 has been canceled because of lack of funding.
