### ISSUE TITLE
Allow to set an `Accept` header 

### ISSUE THREAD

**Issue by Laxystem** [filip26/titanium-json-ld#306]
I'm trying to implement ActivityPub. In order to do so, I decided to start with parsing the output of `mastoson.social/users/mastodon`. *However*, Titanium just complains that it doesn't support `text/html` - as mastodon replies by default with its website. I need to pass an `Accept` header of `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` in order to get JSON LD. However, it is impossible to change the `DocumentLoaderOptions` parameter (that has the `requestProfile` property), as it is created when calling `.get()`.

I'm using Titanium v1.3.3 (as it appears to be the latest). Judging by the README, it seems like it is possible to change the `timeout`, which is a part of `DocumentLoaderOptions` in version 1.4.0, which I assume isn't released yet?

Is there a reason that class is created inside the method, instead of being configurable?

Additionally, there seems to be no way to change the header itself from `application/ld+json` to, for example, `application/activity+json`.

# Workaround
Create an `HttpLoader` with an `HttpClient` delegating to another, overriding the `requestProfile` parameter. Kotlin example below.
```kotlin
private val loader = HttpLoader { targetUri, _ ->
    DefaultHttpClient.defaultInstance().send(targetUri, "application/activity+json")
}
```

**Comment by filip26** [comment]
Hi, 
the loader options are set by processing algorithms according to the specification programmatically for a reason. Please see JSON-LD 1.1 spec for details. Also, see [ProfileConstans](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/jsonld/http/ProfileConstants.java)

If you like to set your custom accept header, which could cause a processor malfunction, then please implement your own [DocumentLoader](https://github.com/filip26/titanium-json-ld/blob/main/src/main/java/com/apicatalog/jsonld/loader/DocumentLoader.java) 

In a case that a server returns JSON but a wrong- `content type` for some reason, you can set fallback `content-type`. See https://github.com/filip26/titanium-json-ld/issues/132
