### ISSUE TITLE
Type Coercion not working in a @container inside another @container

### ISSUE THREAD

**Issue by hyprdia** [filip26/titanium-json-ld#333]
**Describe the bug**

Type coecion is not applied when a `@container` is defined inside another `@container`. In the example below I define friends as a container:

```json-ld
...
"friends": {
  "@id": "core:User@1/core:Friends",
  "@type": "@id",
  "@container": [
    "@id",
    "@set"
  ]
}
...
```

This container is present inside the top `users` container: 

```json-ld
...
"users": {
  "@id": "core:Group@1/core:Users",
  "@container": "@set"
}
...
```

**To Reproduce**

Here is a test that will reproduce the bug:

```java
    @Test
    void titaniumExpansionTest() throws JsonLdError {

        String jsonString = """
            {
              "@context": {
                "@base": "https://api.example.com/data/",
                "core": "https://api.example.com/classes/core:",
                "sh": "http://www.w3.org/ns/shacl#",
                "xsd": "http://www.w3.org/2001/XMLSchema#",
                "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                "users": {
                  "@id": "core:Group@1/core:Users",
                  "@container": "@set"
                },
                "core:User@1": {
                  "@context": {
                    "type": {
                      "@id": "core:User@1/core:Type",
                      "@type": "@id"
                    },
                    "friends": {
                      "@id": "core:User@1/core:Friends",
                      "@type": "@id",
                      "@container": [
                        "@id",
                        "@set"
                      ]
                    },
                    "path": {
                      "@id": "core:User@1/core:Path",
                      "@type": "xsd:string",
                      "@container": "@list"
                    }
                  }
                }
              },
              "@id": "02wBzNotDceDYnLYE2ndhH",
              "@type": "core:Group@1/core:Users",
              "users": {
                "@set": [
                  {
                    "@id": "02wBzNotbWW1ROCZxlUjmw",
                    "@type": "core:User@1",
                    "type": "02w7bdDtd7owQzsKGCALDs",
                    "friends": {
                      "@set": [
                        "02w7bdDtj3RI0BJoMGltwK",
                        "02w7bdDtj3RI08x102ToY2"
                      ]
                    },
                    "path": {
                      "@list": [
                        "john"
                      ]
                    }
                  }
                ]
              }
            }
        """;

        ExpansionApi expanded = JsonLd.expand(
                        JsonDocument.of(
                                new ByteArrayInputStream(
                                        jsonString.getBytes(
                                                StandardCharsets.UTF_8
                                        )
                                )
                        )
                ).mode(JsonLdVersion.V1_1)
                .ordered(true)
                .base("https://api.example.com/");
        
        String expected = """
            [
              {
                "@id": "https://api.example.com/data/02wBzNotDceDYnLYE2ndhH",
                "@type": [
                  "https://api.example.com/classes/core:Group@1/core:Users"
                ],
                "https://api.example.com/classes/core:Group@1/core:Users": [
                  {
                    "@id": "https://api.example.com/data/02wBzNotbWW1ROCZxlUjmw",
                    "@type": [
                      "https://api.example.com/classes/core:User@1"
                    ],
                    "https://api.example.com/classes/core:User@1/core:Friends": [
                      {
                        "@id": "https://api.example.com/data/02w7bdDtj3RI0BJoMGltwK"
                      },
                      {
                        "@id": "https://api.example.com/data/02w7bdDtj3RI08x102ToY2"
                      }
                    ],
                    "https://api.example.com/classes/core:User@1/core:Path": [
                      {
                        "@list": [
                          {
                            "@value": "john"
                          }
                        ]
                      }
                    ],
                    "https://api.example.com/classes/core:User@1/core:Type": [
                      {
                        "@id": "https://api.example.com/data/02w7bdDtd7owQzsKGCALDs"
                      }
                    ]
                  }
                ]
              }
            ]
                """;

        assertEquals(StringUtils.deleteWhitespace(expected), expanded.get().toString());
    }
```

**Expected behavior**

I would expect the values inside the `friends` list to be considered as ids and prepended the defined `@base` but it's not the case, although I take the same source Json and put it inside [Json Playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40base%22%3A%22https%3A%2F%2Fapi.example.com%2Fdata%2F%22%2C%22core%22%3A%22https%3A%2F%2Fapi.example.com%2Fclasses%2Fcore%3A%22%2C%22sh%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%22%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22users%22%3A%7B%22%40id%22%3A%22core%3AGroup%401%2Fcore%3AUsers%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22core%3AUser%401%22%3A%7B%22%40context%22%3A%7B%22type%22%3A%7B%22%40id%22%3A%22core%3AUser%401%2Fcore%3AType%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22friends%22%3A%7B%22%40id%22%3A%22core%3AUser%401%2Fcore%3AFriends%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%5B%22%40id%22%2C%22%40set%22%5D%7D%2C%22path%22%3A%7B%22%40id%22%3A%22core%3AUser%401%2Fcore%3APath%22%2C%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40list%22%7D%7D%7D%7D%2C%22%40id%22%3A%2202wBzNotDceDYnLYE2ndhH%22%2C%22%40type%22%3A%22core%3AGroup%401%2Fcore%3AUsers%22%2C%22users%22%3A%7B%22%40set%22%3A%5B%7B%22%40id%22%3A%2202wBzNotbWW1ROCZxlUjmw%22%2C%22%40type%22%3A%22core%3AUser%401%22%2C%22type%22%3A%2202w7bdDtd7owQzsKGCALDs%22%2C%22friends%22%3A%7B%22%40set%22%3A%5B%2202w7bdDtj3RI0BJoMGltwK%22%2C%2202w7bdDtj3RI08x102ToY2%22%5D%7D%2C%22path%22%3A%7B%22%40list%22%3A%5B%22john%22%5D%7D%7D%5D%7D%7D) and it works.

Here is a screenshot of the differences from Json Playground (on the left, Titanium on the right). Here we can clearly see that type coercion is applied in the Json Playground: 

<img width="1507" alt="Screenshot 2024-04-05 at 9 12 20 AM" src="https://github.com/filip26/titanium-json-ld/assets/79751620/d9197efc-531d-41f8-bdf7-bec1365dc6fb">

**Additional context**

I am using the latest distributed version (`1.4.0`), the same problem is present in Apache Jena 4.10.

**Comment by filip26** [comment]
@hyprdia thank you for reporting the bug, it will be fixed in the next release.

**Comment by filip26** [comment]
It's a bug in `@container: @id` expansion.  `[@index, @set]` container mapping works ok.

**Comment by hyprdia** [comment]
@filip26 Thank you!! I will put this to work pretty soon.
