### ISSUE TITLE
Set the fallbackContentType for the DefaultHttpLoader to JSON (and/or make DefaultHttpLoader public)

### ISSUE THREAD

**Issue by costas80** [filip26/titanium-json-ld#350]
**Is your feature request related to a problem? Please describe.**

I have an issue loading a JSON-LD remote context over HTTP which is (incorrectly) being returned with a Content Type of `text/plain`. Checking the implementation of `DefaultHttpLoader` I see that the resulting error could easily be avoided if the `fallbackContentType` was set to `MediaType.JSON`, exactly as the `FileLoader` already does.

**Describe the solution you'd like**

It seems that this could be very easily resolved if the `fallbackContentType` for `DefaultHttpLoader` were set to `MediaType.JSON`. Alternatively this could be done when setting up your own `DocumentLoader`s whereby we could replace the default `DefaultHttpLoader` with a new instance on which the `fallbackContentType` is set. Frustratingly however, class `DefaultHttpLoader` is not public meaning that I cannot reuse it to create such an instance.

I would suggest two minor updates to resolve this:
* Adapt `DefaultHttpLoader` to set `fallbackContentType` to `MediaType.JSON`.
* Adapt `DefaultHttpLoader` to make it public.

**Describe alternatives you've considered**

The alternative to what I propose would be a complete rewrite (copy basically) of the `DefaultHttpLoader` which seems complete overkill to simply add one method call.

**Additional context**

If you confirm that doing these changes don't break anything I am unaware of, and don't go against any design principles I'd be happy to submit a PR making these changes.

**Comment by filip26** [comment]
Hi,
what about this https://github.com/filip26/titanium-json-ld/issues/132#issuecomment-826282856 ? Does it work for you?

**Comment by costas80** [comment]
Yes it does! Don't know how I missed that... Many thanks @filip26!

**Comment by filip26** [comment]
@costas80 if you have an idea on how to make the code more modular, configurable, then please don't hesitate to open PR. I would only recommend to contact me before making huge changes.

**Comment by costas80** [comment]
No, I think that your solution covers this perfectly. I was trying to work directly with the `DefaultHttpLoader` when in fact using the `HttpLoader` was the way to go. In hindsight we can keep things as-is.
