### ISSUE TITLE
JavaEE dependencies

### ISSUE THREAD

**Issue by acoburn** [filip26/titanium-json-ld#46]
The codebase currently depends on `javax.json:javax.json-api`. Since the JavaEE packages are now being maintained and developed by the Jakarta project, have there been considerations about depending, instead, on `jakarta.json:jakarta.json-api` and the corollary `org.glassfish/jakarta.json`? 

https://search.maven.org/artifact/jakarta.json/jakarta.json-api/1.1.6/bundle
https://search.maven.org/artifact/org.glassfish/jakarta.json/1.1.6/bundle

**Comment by filip26** [comment]
The processor will switch on `Jakarta EE` eventually. The only question is when. More feedback from users is needed here. Not sure how many apps still stick with `Java EE`.

**Comment by acoburn** [comment]
One option would be to set the `javax.json-api` dependency as `provided` scope. That way, when the code that uses this library brings in a JsonP provider, that provider will transitively use the correct version of the json-api.
