### ISSUE TITLE
Cycling JSON->RDF->JSON: dropped data

### ISSUE THREAD

**Issue by martinPikeGB** [filip26/titanium-json-ld#58]
JSON-RDF-JSON issue

In trying to do the json->rdf->json cycle, the 
last entry of the outer list : [7,-7] is lost converting
RDF->JSON

input data:

{
  "https://purl.org/geojson/vocab#coordinates": [{
    "@list": [
      {"@list": [{"@value": 10.0}, {"@value": -10.0}]},
      {"@list": [{"@value": 9.0}, {"@value": -9.0}]},
      {"@list": [{"@value": 8.0}, {"@value": -8.0}]},
      {"@list": [{"@value": 7.0}, {"@value": -7.0}]}
    ]
  }]
 }

code:
	
		String input = 
		"{\n" + 
		"  \"https://purl.org/geojson/vocab#coordinates\": [{\n" + 
		"    \"@list\": [\n" + 
		"      {\"@list\": [{\"@value\": 10.0}, {\"@value\": -10.0}]},\n" + 
		"      {\"@list\": [{\"@value\": 9.0}, {\"@value\": -9.0}]},\n" + 
		"      {\"@list\": [{\"@value\": 8.0}, {\"@value\": -8.0}]},\n" + 
		"      {\"@list\": [{\"@value\": 7.0}, {\"@value\": -7.0}]}\n" + 
		"    ]\n" + 
		"  }]\n" + 
		" }\n" + 
		"";
		
		ByteArrayInputStream stream = new ByteArrayInputStream(input.getBytes());
	
		JsonDocument doc = JsonDocument.of(stream);
		ToRdfApi tt = JsonLd.toRdf(doc);
		RdfDataset rdf = tt.get();
		
		Document rdfDoc = RdfDocument.of(rdf);
		
		FromRdfApi fromRdf = JsonLd.fromRdf(rdfDoc);
		JsonArray array = fromRdf.get();
		System.out.println(array);

**Comment by filip26** [comment]
There is a bug in the implementation of the fromRdf algorithm, the last list item is always dropped.
