### ISSUE TITLE
More meaningful error messages

### ISSUE THREAD

**Issue by jmvanel** [filip26/titanium-json-ld#59]
Except for simple pure JSON syntax errors, there are no meaningful error messages; in many cases all we get is a JsonLdError exception and a stack.

Exemple:
`JsonLd.expand( inatdir + "test-jmv.json").context(inatdir + "test.context.jsonld").get
com.apicatalog.jsonld.api.JsonLdError
  at com.apicatalog.jsonld.expansion.ObjectExpansion1314.expand(ObjectExpansion1314.java:170)
  at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:120)
  at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:123)
  at com.apicatalog.jsonld.expansion.ArrayExpansion.expand(ArrayExpansion.java:101)
  at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:114)
  at com.apicatalog.jsonld.expansion.ObjectExpansion1314.expand(ObjectExpansion1314.java:339)
  at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:120)
  at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:123)
  at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:140)
  at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:62)
  at com.apicatalog.jsonld.api.impl.ExpansionApi.get(ExpansionApi.java:148)
  ... 36 elided`

The JSON data : test-jmv.json
```json
{ "results" : [ {
         "id" : "54141546",
         "place_ids" : [ 97391, 108692 ],
         "map_scale" : null,
         "tags" : [],
         "captive" : false,
         "identifications_some_agree" : false,
         "geoprivacy" : null,
         "uri" : "https://www.inaturalist.org/observations/54141546",
         "quality_grade" : "needs_id",
         "taxon" : null,
         "site_id" : 1,
         "reviewed_by" : [],
         "description" : "Aucune fleur ou fruit, glauque, très drageonnant, pas plus de 40 cm, dans une prairie sèche rarement fauchée",
         "user" : {
            "id" : 3295956,
            "name" : "Jean-Marc Vanel",
            "icon" : "https://static.inaturalist.org/attachments/users/icons/3295956/thumb.jpg?1594113662"
         },
         "created_at" : "2020-07-24T12:03:34+02:00",
  "total_results" : 1,
   "per_page" : 1
} ] }
```

The context:  test.context.jsonld
```json
{
"@context": {
  "results" : "@graph" ,
  "id": "@id",
  "uri": "@id"
} }
```
The URL prefix:
```java
String inatdir = "file:///home/jmv/src/rdf-convert/inaturalist.org/" ;
```
NOTE: removing in context the line "id": "@id", removes the error .

**Comment by filip26** [comment]
Hi,
`JsonLdError` has [getCode()](https://github.com/filip26/titanium-json-ld/blob/87830eda1c2683155771f1a095f7930fdf9bb1c2/src/main/java/com/apicatalog/jsonld/api/JsonLdError.java#L45) getter which returns `JsonLdErrorCode.COLLIDING_KEYWORDS` in your case. 

The context:
```json {
"@context": {
  "results" : "@graph" ,
  "id": "@id",
  "uri": "@id"
} }
```

is not valid JSON-LD context.

The error codes are described in [JsonLdErrorCode](https://github.com/filip26/titanium-json-ld/blob/87830eda1c2683155771f1a095f7930fdf9bb1c2/src/main/java/com/apicatalog/jsonld/api/JsonLdErrorCode.java) and are defined by [JSON-LD 1.1 specification](https://www.w3.org/TR/json-ld11-api/#jsonlderrorcode)

**Comment by jmvanel** [comment]
Indeed COLLIDING_KEYWORDS is a meaningful message !
I did not see it by the default message, neither with Java nor with Scala .
 
I have 2 suggestions:
1. provide a toString() method on JsonLdError that prints  getCode()
2. provide line number


With Scala I use this in the REPL to see the error : 
```scala
var err = Try { JsonLd.toRdf(  inatdir + "observation.jmv.json" ) .
  context( inatdir + "test.context.jsonld") .get }
err match { case Failure(e) => e.asInstanceOf[JsonLdError] . getCode
            case Success(s) => s }
```

**Comment by filip26** [comment]
It's hard to provide line numbers, but it could be possible to return JsonPath. I've created a new issue #71 to address that.
