### ISSUE TITLE
JsonLd.toRdf takes a long time for a specific example

### ISSUE THREAD

**Issue by kevinpeterson** [filip26/titanium-json-ld#62]
**Describe the bug**
I think there may be a performance issue when contexts recurse. I have a small example that does complete, but takes several minutes.

**To Reproduce**
See the JSONLD content to reproduce is here: https://tinyurl.com/y4jlpkz5

I plug that into ``JsonLd.toRdf`` as such:

```
ToRdfApi rdf = JsonLd.toRdf(stream).options(jsonLdOptions);
RdfDataset dataset = rdf.get();
```

**Expected behavior**
I would expect a small example like this to be fairly fast. I suspect there is some looping or something that can be optimized.

**Comment by kevinpeterson** [comment]
Also, I've noticed that if I comment out the following lines in ``TermDefinitionBuilder`` it works fine and is much faster:

https://github.com/filip26/titanium-json-ld/blob/6b6dea3d7c0831913161a2841b3cca3f647bcdbd/src/main/java/com/apicatalog/jsonld/context/TermDefinitionBuilder.java#L519-L524

but there are four unit tests that then fail (testExpand#tc032, testExpand#tc033, testToRdf#tc032:, testToRdf#tc033).

These seem to be related to checking for appropriate exceptions. With those lines commented out, the processing (at least using my json test files) seems to still be fine though.

Is that an area that can be optimized somehow (short of commenting it out)? I'd be happy to work on it, but I might need a few pointers on direction.

**Comment by filip26** [comment]
Thank you for the report, the issue is that an already processed remote context is not properly cached and is fetched and processed again and again. It's definitely a bug that occurs when there are many inter-referenced remote contexts.

**Comment by filip26** [comment]
https://github.com/filip26/titanium-json-ld/blob/6b6dea3d7c0831913161a2841b3cca3f647bcdbd/src/main/java/com/apicatalog/jsonld/context/ActiveContextBuilder.java#L456

The `fetch` method must use a cache of processed contexts and stop after 5.2.3 if a context has been processed already.

**Comment by filip26** [comment]
some numbers (using experimental cache) 

contexts: 66
contexts fetch time  9.05s 
total processing time:  9.5s

**Comment by filip26** [comment]
@kevinpeterson  just a note, I've noticed that the remote contexts you use don't have `Cache-Control` or `Expires` HTTP header. It does not help with this issue, but it can improve fetch time in a case of repeating requests.

**Comment by kevinpeterson** [comment]
@filip26 Ok, that is good to know, thank you.

**Comment by filip26** [comment]
Update: v2.0.0-M3 completes the test 

https://github.com/filip26/titanium-json-ld/blob/f7a1c080dcc3fbf17a396e484a05e0aeb8d7d952/src/test/java/com/apicatalog/jsonld/custom/RemoteContextTest.java#L162

in under 30 seconds on my computer. Feedback and contributions on v2 are welcome.
