### ISSUE TITLE
The @base attribute is only used if the remote contexts list is empty.

### ISSUE THREAD

**Issue by kevinpeterson** [filip26/titanium-json-ld#63]
**Describe the bug**

The ``@base`` attribute is only used if the remote contexts list is empty.

**To Reproduce**

Populate the ``@base`` attribute along with one or more entries in the remote contexts.

For example, I would expect this to result in one triple when going to RDF:

```
{
  "@id": "1",
  "test": "some-test",
  "@context": [
    "https://fhircat.org/fhir-r5/original/contexts/careplan.context.jsonld",
    {
      "nodeRole": {
        "@type": "@id",
        "@id": "fhir:nodeRole"
      },
      "@base": "http://hl7.org/fhir/",
      "owl:imports": {
        "@type": "@id"
      },
      "owl:versionIRI": {
        "@type": "@id"
      }
    }
  ]
}
```

**Expected behavior**

I believe the correct interpretation of this spec is that ``@base`` should be considered if the context is not a remote context (not necessarily if the remote contexts list is empty). See linked issue below.

**Additional context**

https://github.com/w3c/json-ld-api/issues/505

**Comment by filip26** [comment]
Hi,
thank you for reporting this. 
```
<http://hl7.org/fhir/1> <http://example.com/UNKNOWN#test> "some-test" .
```
@kevinpeterson please, can you confirm this is the expected output?

**Comment by filip26** [comment]
duplicate #61

**Comment by filip26** [comment]
Quite, confusing, I'll go with removing @base from a remote context after 5.2.5.2 as suggested.
