### ISSUE TITLE
Use native types generate an invalid json ld

### ISSUE THREAD

**Issue by skomlaebri** [filip26/titanium-json-ld#64]
**Describe the bug**
Setting use native types to true return an invalid json ld:  all string literals are converted to a value with xsd:string attached.

**To Reproduce**

```
JsonLdOptions  jlo = new JsonLdOptions();
jlo.setUseNativeTypes(true);
JsonArray rdf = JsonLd.fromRdf(RdfDocument.of(streamResult)).options(jlo).get();
```

The variable streamResult contains the example 1 of [rdf nq](https://www.w3.org/TR/n-quads/)
```
<http://one.example/subject1> <http://one.example/predicate1> <http://one.example/object1> <http://example.org/graph3> .
_:subject1 <http://an.example/predicate1> "object1" <http://example.org/graph1> .
_:subject2 <http://an.example/predicate2> 1^^<http://www.w3.org/2001/XMLSchema#integer> <http://example.org/graph5> .
```

The obtained result is 
`[{"@id":"http://example.org/graph1","@graph":[{"@id":"_:subject1","http://an.example/predicate1":[{"@value":"object1^^http://www.w3.org/2001/XMLSchema#string"}]}]},{"@id":"http://example.org/graph3","@graph":[{"@id":"http://one.example/subject1","http://one.example/predicate1":[{"@id":"http://one.example/object1"}]}]},{"@id":"http://example.org/graph5","@graph":[{"@id":"_:subject2","http://an.example/predicate2":[{"@value":1}]}]}]`

**"@value":"object1^^http://www.w3.org/2001/XMLSchema#string"** is an invalid format, the correct value would be
{"@value":"object1"} or {"@value":"object1","@type":"http://www.w3.org/2001/XMLSchema#string"}. 

**Expected behavior**
Using useNativeTypes I would expect the object1 that is a string to become a simple {"@value":"object1"} without the type.
With the current example full result:
`[{"@id":"http://example.org/graph1","@graph":[{"@id":"_:subject1","http://an.example/predicate1":[{"@value":"object1"}]}]},{"@id":"http://example.org/graph3","@graph":[{"@id":"http://one.example/subject1","http://one.example/predicate1":[{"@id":"http://one.example/object1"}]}]},{"@id":"http://example.org/graph5","@graph":[{"@id":"_:subject2","http://an.example/predicate2":[{"@value":1}]}]}]`

**Comment by filip26** [comment]
Hi,
thank you for reporting the issue. Please note v0.8.5 adds a new method nativeTypes().

e.g.
```javascript
JsonLd.fromRdf(..).nativeTypes().get()
```
See [FromRdfApi](https://github.com/filip26/titanium-json-ld/blob/master/src/main/java/com/apicatalog/jsonld/api/impl/FromRdfApi.java#L96)
