### ISSUE TITLE
Consideration on performance

### ISSUE THREAD

**Issue by umbreak** [filip26/titanium-json-ld#69]
This is just informative and for no means with any aim to criticise. I think the code is written very tidily and it is great to have an alternative to Json-LD Java.

I did some benchmarks comparing Json-LD Java with Titanium using the W3C compliance test suite (just the subset that Json-LD Java supported). Please [take a look at the results](https://github.com/umbreak/jsonld-benchmarks#results). 

I think it is normal performance in Json-LD Java is higher due to the lesser complexity of Json-LD 1.0 spec. Also due to their maturity they had the chance to improve performance. But I'm sure there is a room for performance improvement on this project too.

**Comment by filip26** [comment]
That's a great input. Thank you! A profiling is needed to understand where bottlenecks are.

**Comment by filip26** [comment]
related to #62

**Comment by filip26** [comment]
@umbreak 0.8.6 includes a few minor performance tweaks. btw. does the benchmark result include (de)serialization time?

**Comment by umbreak** [comment]
I've updated the repository with the latest titanium dependency and I can see an increase in performance. **The global ratio between all operations Json-LD Java vs. Titanium was at 12.88 and now is at 9.91**.

It take into consideration serialization for both libraries, so that should be neglected since it is a relative comparison.

**Comment by filip26** [comment]
link to #184
