### ISSUE TITLE
Support for URDNA2015?

### ISSUE THREAD

**Issue by peacekeeper** [filip26/titanium-json-ld#84]
Is anyone working on adding support for the URDNA2015 [RDF Dataset Normalization](https://json-ld.github.io/normalization/spec/) algorithm? 

[jsonld-java supports URGNA2012](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/NormalizeUtils.java), but that's outdated...

**Comment by filip26** [comment]
Hi, please feel free to open PR.

**Comment by simon-greatrix** [comment]
I have an implementation of URDNA2015:

https://github.com/simon-greatrix/rdf-urdna

**Comment by peacekeeper** [comment]
@simon-greatrix great, are you planning to release this under Apache 2 license and/or merge it into this project here?

**Comment by filip26** [comment]
Hi @simon-greatrix,
URDNA is a complementary technology to JSON-LD,  not needed to perform JSON-LD algorithms nor required by every user. It's a great extension that should be distributed as a standalone library. 

Titanium is an open project and welcomes a contribution. Your implementation could be included as an extension (root project directory refactoring is needed) if:

* Licensing, IPO, of your code is resolved. As far as I understand IPO holds your employer and it would be unfortunate to put whole Titanium code at risk in a case of unresolved relations
* You plan to contribute to Titanium in the future and you are willing to maintain URDNA code

Anyway, you make me realize that it would be great to have a list of projects using and extending Titanium as part of the project's README.

**Comment by simon-greatrix** [comment]
@peacekeeper My employers decided to debate our entire open source strategy so it took a lot longer than expected. I have now released my URDNA implementation under Apache 2.

For the time being, I will be maintaining it as a separate library rather than as part of Titanium.

**Comment by peacekeeper** [comment]
@simon-greatrix thanks a lot! I also did my own implementation just a few days before you mentioned yours: https://github.com/decentralized-identity/jsonld-common-java/tree/master/src/main/java/foundation/identity/jsonld/normalization

But I think I will use yours going forward. Closing this.
