### ISSUE TITLE
Support for URDNA2015

### ISSUE THREAD

**Issue by peacekeeper** [filip26/titanium-json-ld#85]
Is anyone working on adding support for the URDNA2015 [RDF Dataset Normalization](https://json-ld.github.io/normalization/spec/) algorithm? 

[jsonld-java supports URGNA2012](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/NormalizeUtils.java), but that's outdated...

**Comment by filip26** [comment]
#84 duplicate

**Comment by peacekeeper** [comment]
Sorry for duplicate
