### ISSUE TITLE
export plain GeoJSON from GeoJSON-LD: issues RDF lists + key should be unprefixed

### ISSUE THREAD

**Issue by jmvanel** [filip26/titanium-json-ld#89]
With JsonLd.toRdf() and an expandContext, plus my code to convert Titanium Dataset to Jena Dataset,
I was able to get RDF from a plain JSON .
( FYI see code https://github.com/jmvanel/semantic_forms/blob/master/scala/forms_play/app/controllers/Json2RDFServiceApp.scala#L43 )

Now I have the converse requirement. I want to export GeoJSON (being both plain GeoJSON & JSON-LD) from URI's having geographic data in a Jena TDB database.
See code 
https://github.com/jmvanel/semantic_forms/blob/master/scala/geo/src/main/scala/jmvanel/GeoJSONexport.scala#L116
The issue is that I get mostly plain JSON with an `@context` : 
```json
    {
      "id": "http://semantic-forms.cc:1952/ldp/1511781044277-27461991065971051",
      "type": "Feature",
      "geometry": {
        "id": "406d4e19-bffb-4a8d-ba3e-2e9e7fadba17",
        "type": "Point",
        "geojson:coordinates": {
          "id": "c8d09a13-8359-49b5-819f-d76cce691faf",
          "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": "4.8193165",
          "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": {
            "id": "0194e207-ce2d-4377-9b33-1f397aa773cf",
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": "45.9361934",
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": {
              "@list": []
            }
          }
        }
      },
      "properties": {
```

But there 2 issues:
1. "geojson:coordinates" instead of "coordinates" ; but maybe the original context from https://geojson.org/geojson-ld/ is wrong here 
2. RDF lists are not output as JSON arrays

cf GeoJSON-LD example https://geojson.org/geojson-ld/
This example **works fine** with the JSON-LD distiller
http://rdf.greggkellogg.net/distiller?command=compact&format=jsonld&output_format=jsonld&useNativeTypes
that is, the JSON-LD processor outputs is a plain JSON with an `@context` , and "coordinates" key is correct, and JSON array is present .

**Comment by filip26** [comment]
Hi @jmvanel ,
thank you for reporting this.

Please help me to prepare a test case. I understand that you do `fromRdf` transformation and then you apply `frame` transformation on the result . Not sure which transformation is erroneous, maybe both.

I can download the GeoJSON-LD context but it would be very helpful if you can provide an example of RDF input that produces the wrong result.

FYI: I've noticed a couple of things in your code:
[here is duplicated code - line 118](https://github.com/jmvanel/semantic_forms/blob/272992675014cae26db7e5bf5cb67a0f329c2570/scala/geo/src/main/scala/jmvanel/GeoJSONexport.scala#L121)
[the GeoJSON-LD context is passed as a frame, not as a context](https://github.com/jmvanel/semantic_forms/blob/272992675014cae26db7e5bf5cb67a0f329c2570/scala/geo/src/main/scala/jmvanel/GeoJSONexport.scala#L129) 

Best regards,
Filip

**Comment by jmvanel** [comment]
I provide a simpler example, only JSON-LD input on frame algorithm, that produces the wrong result.

P.S. Did not understand your comment "the GeoJSON-LD context is passed as a frame, not as a context"

```
package jmvanel;
import java.io.FileWriter;
import java.io.IOException;
import com.apicatalog.jsonld.JsonLd;
import com.apicatalog.jsonld.document.Document;
import com.apicatalog.jsonld.document.DocumentParser;
import com.apicatalog.jsonld.http.media.MediaType;
import java.io.StringReader;
import javax.json.Json;
import javax.json.JsonObject;
import javax.json.JsonWriter;
import com.apicatalog.jsonld.api.JsonLdError;
import com.apicatalog.jsonld.api.JsonLdOptions;

/** - read expanded JSON-LD
 *  - frame with GEOJSON context */
public class GeoJSONexportTest {

	static String jsonInputExpanded = "[\n" + 
			"  {\n" + 
			"    \"@id\": \"https://semantic-forms.cc:1953/ldp/1532706288331-48387235120480835\",\n" + 
			"    \"https://purl.org/geojson/vocab#properties\": [\n" + 
			"      {\n" + 
			"        \"@id\": \"f8c50b76-83d0-4cf1-ac6d-ec620eaeb449\"\n" + 
			"      }\n" + 
			"    ],\n" + 
			"    \"https://purl.org/geojson/vocab#geometry\": [\n" + 
			"      {\n" + 
			"        \"@id\": \"e01148c8-2148-4ae4-b6e3-5c941a299ce9\"\n" + 
			"      }\n" + 
			"    ],\n" + 
			"    \"@type\": [\n" + 
			"      \"https://purl.org/geojson/vocab#Feature\"\n" + 
			"    ]\n" + 
			"  },\n" + 
			"  {\n" + 
			"    \"@id\": \"e01148c8-2148-4ae4-b6e3-5c941a299ce9\",\n" + 
			"    \"https://purl.org/geojson/vocab#coordinates\": [\n" + 
			"      {\n" + 
			"        \"@id\": \"a61c31ed-1375-43a5-b875-fb2079213265\"\n" + 
			"      }\n" + 
			"    ],\n" + 
			"    \"@type\": [\n" + 
			"      \"https://purl.org/geojson/vocab#Point\"\n" + 
			"    ]\n" + 
			"  },\n" + 
			"  {\n" + 
			"    \"@id\": \"a61c31ed-1375-43a5-b875-fb2079213265\",\n" + 
			"    \"http://www.w3.org/1999/02/22-rdf-syntax-ns#rest\": [\n" + 
			"      {\n" + 
			"        \"@id\": \"44c4e184-7fdf-48f6-8f97-943623fdcc52\"\n" + 
			"      }\n" + 
			"    ],\n" + 
			"    \"http://www.w3.org/1999/02/22-rdf-syntax-ns#first\": [\n" + 
			"      {\n" + 
			"        \"@value\": \"0.9016695\"\n" + 
			"      }\n" + 
			"    ]\n" + 
			"  },\n" + 
			"    {\n" + 
			"    \"@id\": \"44c4e184-7fdf-48f6-8f97-943623fdcc52\",\n" + 
			"    \"http://www.w3.org/1999/02/22-rdf-syntax-ns#rest\": [\n" + 
			"      {\n" + 
			"        \"@list\": []\n" + 
			"      }\n" + 
			"    ],\n" + 
			"    \"http://www.w3.org/1999/02/22-rdf-syntax-ns#first\": [\n" + 
			"      {\n" + 
			"        \"@value\": \"46.8332179\"\n" + 
			"      }\n" + 
			"    ]\n" + 
			"  }\n" + 
			"]\n" + 
			"";
	static String jsonInput = jsonInputExpanded;

	  // From https://geojson.org/geojson-ld/geojson-context.jsonld
	  static String geojsonContext = "{	  \"@context\": {\n" + 
	  		"	    \"geojson\": \"https://purl.org/geojson/vocab#\",\n" + 
	  		"	    \"Feature\": \"geojson:Feature\",\n" + 
	  		"	    \"FeatureCollection\": \"geojson:FeatureCollection\",\n" + 
	  		"	    \"GeometryCollection\": \"geojson:GeometryCollection\",\n" + 
	  		"	    \"LineString\": \"geojson:LineString\",\n" + 
	  		"	    \"MultiLineString\": \"geojson:MultiLineString\",\n" + 
	  		"	    \"MultiPoint\": \"geojson:MultiPoint\",\n" + 
	  		"	    \"MultiPolygon\": \"geojson:MultiPolygon\",\n" + 
	  		"	    \"Point\": \"geojson:Point\",\n" + 
	  		"	    \"Polygon\": \"geojson:Polygon\",\n" + 
	  		"	    \"bbox\": {\n" + 
	  		"	      \"@container\": \"@list\",\n" + 
	  		"	      \"@id\": \"geojson:bbox\"\n" + 
	  		"	    },\n" + 
	  		"	    \"coordinates\": {\n" + 
	  		"	      \"@container\": \"@list\",\n" + 
	  		"	      \"@id\": \"geojson:coordinates\"\n" + 
	  		"	    },\n" + 
	  		"	    \"features\": {\n" + 
	  		"	      \"@container\": \"@set\",\n" + 
	  		"	      \"@id\": \"geojson:features\"\n" + 
	  		"	    },\n" + 
	  		"	    \"geometry\": \"geojson:geometry\",\n" + 
	  		"	    \"id\": \"@id\",\n" + 
	  		"	    \"properties\": \"geojson:properties\",\n" + 
	  		"	    \"type\": \"@type\"\n" + 
	  		"	  }\n" + 
	  		"	}";


	static String fileName = "out.test.geojson";
      
	public static void main(String[] args) throws JsonLdError, IOException {
		// String url = "https://geojson.org/geojson-ld/geojson-context.jsonld";
		FileWriter fw = new FileWriter(fileName);

		JsonLdOptions options = new JsonLdOptions();
		options.setUseNativeTypes(true);
		options.setOmitGraph(true);
		options.setCompactToRelative(true);
		options.setUseNativeTypes(true);

		Document contextDocument = makeJSONLDdocument(geojsonContext);
		Document jsonDoc = makeJSONLDdocument(jsonInput);
		JsonObject jsonObject = JsonLd.frame(jsonDoc, contextDocument).options(options).get();

		JsonWriter jsonWriter = Json.createWriter(fw);
		jsonWriter.writeObject(jsonObject);
		jsonWriter.close();
	}

	static Document makeJSONLDdocument(String src) throws JsonLdError {
		StringReader inputStream = new StringReader(src);
		return DocumentParser.parse(MediaType.JSON_LD, inputStream);
	}
}
```

**Comment by filip26** [comment]
I'm sorry but I cannot reproduce the issue (tested against latest code base - 0.8.6-SNAPSHOT). The provided test produces the same output as [json-ld playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%5B%7B%22%40id%22%3A%22https%3A%2F%2Fsemantic-forms.cc%3A1953%2Fldp%2F1532706288331-48387235120480835%22%2C%22https%3A%2F%2Fpurl.org%2Fgeojson%2Fvocab%23properties%22%3A%5B%7B%22%40id%22%3A%22f8c50b76-83d0-4cf1-ac6d-ec620eaeb449%22%7D%5D%2C%22https%3A%2F%2Fpurl.org%2Fgeojson%2Fvocab%23geometry%22%3A%5B%7B%22%40id%22%3A%22e01148c8-2148-4ae4-b6e3-5c941a299ce9%22%7D%5D%2C%22%40type%22%3A%5B%22https%3A%2F%2Fpurl.org%2Fgeojson%2Fvocab%23Feature%22%5D%7D%2C%7B%22%40id%22%3A%22e01148c8-2148-4ae4-b6e3-5c941a299ce9%22%2C%22https%3A%2F%2Fpurl.org%2Fgeojson%2Fvocab%23coordinates%22%3A%5B%7B%22%40id%22%3A%22a61c31ed-1375-43a5-b875-fb2079213265%22%7D%5D%2C%22%40type%22%3A%5B%22https%3A%2F%2Fpurl.org%2Fgeojson%2Fvocab%23Point%22%5D%7D%2C%7B%22%40id%22%3A%22a61c31ed-1375-43a5-b875-fb2079213265%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23rest%22%3A%5B%7B%22%40id%22%3A%2244c4e184-7fdf-48f6-8f97-943623fdcc52%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23first%22%3A%5B%7B%22%40value%22%3A%220.9016695%22%7D%5D%7D%2C%7B%22%40id%22%3A%2244c4e184-7fdf-48f6-8f97-943623fdcc52%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23rest%22%3A%5B%7B%22%40list%22%3A%5B%5D%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23first%22%3A%5B%7B%22%40value%22%3A%2246.8332179%22%7D%5D%7D%5D&frame=%7B%22%40context%22%3A%7B%22geojson%22%3A%22https%3A%2F%2Fpurl.org%2Fgeojson%2Fvocab%23%22%2C%22Feature%22%3A%22geojson%3AFeature%22%2C%22FeatureCollection%22%3A%22geojson%3AFeatureCollection%22%2C%22GeometryCollection%22%3A%22geojson%3AGeometryCollection%22%2C%22LineString%22%3A%22geojson%3ALineString%22%2C%22MultiLineString%22%3A%22geojson%3AMultiLineString%22%2C%22MultiPoint%22%3A%22geojson%3AMultiPoint%22%2C%22MultiPolygon%22%3A%22geojson%3AMultiPolygon%22%2C%22Point%22%3A%22geojson%3APoint%22%2C%22Polygon%22%3A%22geojson%3APolygon%22%2C%22bbox%22%3A%7B%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22geojson%3Abbox%22%7D%2C%22coordinates%22%3A%7B%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22geojson%3Acoordinates%22%7D%2C%22features%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40id%22%3A%22geojson%3Afeatures%22%7D%2C%22geometry%22%3A%22geojson%3Ageometry%22%2C%22id%22%3A%22%40id%22%2C%22properties%22%3A%22geojson%3Aproperties%22%2C%22type%22%3A%22%40type%22%7D%7D).

**Comment by jmvanel** [comment]
The processing chain here is quite long:

1. getting a SPARQL query in Jena TDB, including blank nodes
2. converting to Titanium RDF Dataset
3. running JsonLd.fromRdf()
4. running JsonLd.frame()

and in the end, the JSON array corresponding to RDF list is not present.
 
I finally found the location of error, in step 3, giving this issue : #118
So I can close the issue :) .
